import 'dart:async';

import 'package:animations/animations.dart';
import 'package:flutter/material.dart';
import 'package:serverpod_auth_core_flutter/serverpod_auth_core_flutter.dart';

import '../common/widgets/buttons/action_button.dart';
import '../common/widgets/buttons/text_button.dart';
import '../common/widgets/gaps.dart';
import '../email/email_auth_controller.dart' show EmailAuthState;
import '../email/forms/verification.dart';
import '../email/forms/widgets/email_text_field.dart';
import '../email/forms/widgets/form_standard_layout.dart';
import '../email/forms/widgets/terms_and_privacy.dart';
import '../localization/sign_in_localization_provider.dart';
import 'email_passwordless_auth_controller.dart';

export '../email/forms/verification.dart' show VerificationCodeConfig;

/// A widget that provides passwordless email authentication: the user enters
/// an email address, receives a verification code, and enters it to sign in.
/// An account is created when the email address is new, unless sign-up is
/// disabled on the server.
///
/// The server must expose an endpoint extending `EmailPasswordlessIdpBaseEndpoint`.
///
/// The widget can manage its own [EmailPasswordlessAuthController], or you can
/// provide an external [controller].
///
/// Example with managed state:
/// ```dart
/// EmailPasswordlessSignInWidget(
///   client: client,
///   onAuthenticated: () => Navigator.push(...),
///   onError: (error) => showSnackBar(...),
/// )
/// ```
///
/// When used inside a `SignInWidget` together with the email and password
/// widget, see `SignInWidget` for which of the two is shown.
///
/// Related issue: https://github.com/serverpod/serverpod/issues/2100.
class EmailPasswordlessSignInWidget extends StatefulWidget {
  /// Controls the authentication state and behavior.
  ///
  /// If null, the widget creates and manages its own controller, and [client]
  /// must be provided. If provided, [client], [onAuthenticated], [onError] and
  /// [emailValidation] are handled by the controller and must not be passed.
  final EmailPasswordlessAuthController? controller;

  /// The Serverpod client instance.
  ///
  /// Required when [controller] is null, ignored otherwise.
  final ServerpodClientShared? client;

  /// Callback when authentication is successful.
  ///
  /// Ignored when [controller] is provided.
  final VoidCallback? onAuthenticated;

  /// Callback when an error occurs during authentication.
  ///
  /// Ignored when [controller] is provided.
  final Function(Object error)? onError;

  /// The validation function to use for email validation.
  ///
  /// Ignored when [controller] is provided.
  final void Function(String email)? emailValidation;

  /// Configuration for the verification code input.
  ///
  /// Defaults to the 6 digit codes generated by the server by default. Make
  /// sure to match the configuration of the code generated by the server, and
  /// to set a [VerificationCodeConfig.resendCountdownDuration] at least as long
  /// as the resend cooldown of the server.
  final VerificationCodeConfig? verificationCodeConfig;

  /// A widget shown below the email field on the email entry screen to inform
  /// the user about terms and conditions, a privacy policy, or any other
  /// consent that applies to creating an account.
  ///
  /// As sign-up happens implicitly when an unknown email address is verified,
  /// this is the place to show the consent notice, for example a short
  /// `Text.rich` with links. Keep it compact, the email entry screen has a
  /// fixed height.
  ///
  /// This is a notice and does not block the continue button. To require an
  /// explicit acceptance, use [onTermsAndConditionsPressed] and
  /// [onPrivacyPolicyPressed] instead. If both are given, [consentNotice] is
  /// shown.
  final Widget? consentNotice;

  /// Optional callback to call when the terms and conditions button is pressed.
  ///
  /// If this or [onPrivacyPolicyPressed] is provided, and no [consentNotice]
  /// is, a checkbox that has to be checked before a code is requested is shown.
  final VoidCallback? onTermsAndConditionsPressed;

  /// Optional callback to call when the privacy policy button is pressed.
  ///
  /// See [onTermsAndConditionsPressed].
  final VoidCallback? onPrivacyPolicyPressed;

  /// Creates a passwordless email sign-in widget.
  const EmailPasswordlessSignInWidget({
    this.controller,
    this.client,
    this.onAuthenticated,
    this.onError,
    this.emailValidation,
    this.verificationCodeConfig,
    this.consentNotice,
    this.onTermsAndConditionsPressed,
    this.onPrivacyPolicyPressed,
    super.key,
  }) : assert(
         (controller == null) != (client == null),
         'Either controller or client must be provided, but not both. When '
         'passing a controller, client, onAuthenticated, onError and '
         'emailValidation parameters are ignored.',
       ),
       assert(
         (onAuthenticated == null &&
                 onError == null &&
                 emailValidation == null) ||
             controller == null,
         'Do not provide onAuthenticated, onError or emailValidation when '
         'using a controller as they will be handled by the controller.',
       );

  @override
  State<EmailPasswordlessSignInWidget> createState() =>
      _EmailPasswordlessSignInWidgetState();
}

class _EmailPasswordlessSignInWidgetState
    extends State<EmailPasswordlessSignInWidget> {
  late final EmailPasswordlessAuthController _controller;

  @override
  void initState() {
    super.initState();
    _controller =
        widget.controller ??
        EmailPasswordlessAuthController(
          client: widget.client!,
          onAuthenticated: widget.onAuthenticated,
          onError: widget.onError,
          emailValidation: widget.emailValidation,
        );
    _controller.addListener(_onControllerChanged);
  }

  @override
  void dispose() {
    _controller.removeListener(_onControllerChanged);
    if (widget.controller == null) {
      _controller.dispose();
    }
    super.dispose();
  }

  void _onControllerChanged() {
    if (mounted) setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return PageTransitionSwitcher(
      duration: const Duration(milliseconds: 600),
      reverse: _controller.currentScreen != EmailPasswordlessFlowScreen.start,
      transitionBuilder: (child, primaryAnimation, secondaryAnimation) {
        return SharedAxisTransition(
          animation: primaryAnimation,
          secondaryAnimation: secondaryAnimation,
          transitionType: SharedAxisTransitionType.horizontal,
          fillColor: Colors.transparent,
          child: child,
        );
      },
      child: switch (_controller.currentScreen) {
        EmailPasswordlessFlowScreen.start => EmailPasswordlessStartForm(
          key: const ValueKey('start'),
          controller: _controller,
          consentNotice: widget.consentNotice,
          onTermsAndConditionsPressed: widget.onTermsAndConditionsPressed,
          onPrivacyPolicyPressed: widget.onPrivacyPolicyPressed,
        ),
        EmailPasswordlessFlowScreen.verify => EmailPasswordlessVerifyForm(
          key: const ValueKey('verify'),
          controller: _controller,
          verificationCodeConfig:
              widget.verificationCodeConfig ??
              VerificationCodeConfig.numbersOnly(length: 6),
        ),
      },
    );
  }
}

/// The email entry form of the passwordless email flow.
class EmailPasswordlessStartForm extends StatelessWidget {
  /// The controller that manages authentication state and logic.
  final EmailPasswordlessAuthController controller;

  /// See [EmailPasswordlessSignInWidget.consentNotice].
  final Widget? consentNotice;

  /// See [EmailPasswordlessSignInWidget.onTermsAndConditionsPressed].
  final VoidCallback? onTermsAndConditionsPressed;

  /// See [EmailPasswordlessSignInWidget.onPrivacyPolicyPressed].
  final VoidCallback? onPrivacyPolicyPressed;

  /// Creates an [EmailPasswordlessStartForm].
  const EmailPasswordlessStartForm({
    required this.controller,
    this.consentNotice,
    this.onTermsAndConditionsPressed,
    this.onPrivacyPolicyPressed,
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    final texts = context.emailPasswordlessSignInTexts;
    final consentNotice = this.consentNotice;
    final requiresAcceptance =
        consentNotice == null &&
        (onTermsAndConditionsPressed != null || onPrivacyPolicyPressed != null);

    return FormStandardLayout(
      title: texts.title,
      content: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Text(
            texts.description,
            style: Theme.of(context).textTheme.bodyMedium,
          ),
          smallGap,
          EmailTextField(controller: controller),
          if (consentNotice != null) ...[
            smallGap,
            DefaultTextStyle.merge(
              style: Theme.of(context).textTheme.bodySmall,
              child: consentNotice,
            ),
          ] else if (requiresAcceptance) ...[
            const Expanded(child: SizedBox.shrink()),
            SizedBox(
              height: 40,
              child: TermsAndPrivacyText(
                onTermsAndConditionsPressed: onTermsAndConditionsPressed,
                onPrivacyPolicyPressed: onPrivacyPolicyPressed,
                isChecked: controller.legalNoticeAcceptedNotifier.value,
                onCheckboxChanged: (value) =>
                    controller.legalNoticeAcceptedNotifier.value =
                        value ?? false,
              ),
            ),
            smallGap,
          ],
        ],
      ),
      actionButton: ActionButton(
        onPressed:
            controller.emailController.text.isNotEmpty &&
                controller.state == EmailAuthState.idle &&
                (!requiresAcceptance ||
                    controller.legalNoticeAcceptedNotifier.value)
            ? () => unawaited(controller.startLogin())
            : null,
        label: texts.continueAction,
        isLoading: controller.isLoading,
      ),
    );
  }
}

/// The verification code form of the passwordless email flow.
class EmailPasswordlessVerifyForm extends StatelessWidget {
  /// The controller that manages authentication state and logic.
  final EmailPasswordlessAuthController controller;

  /// Configuration for the verification code input.
  final VerificationCodeConfig verificationCodeConfig;

  /// Creates an [EmailPasswordlessVerifyForm].
  const EmailPasswordlessVerifyForm({
    required this.controller,
    required this.verificationCodeConfig,
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    final texts = context.emailPasswordlessSignInTexts;

    return VerificationForm(
      title: texts.verifyTitle,
      messageText: texts.verificationMessage,
      verifyButtonLabel: texts.verify,
      controller: controller,
      onCompleted: () => unawaited(controller.finishLogin()),
      verificationCodeConfig: verificationCodeConfig,
      bottomText: Center(
        child: HyperlinkTextButton(
          onPressed: controller.navigateToStart,
          padding: const EdgeInsets.symmetric(horizontal: 8),
          label: texts.useDifferentEmail,
        ),
      ),
    );
  }
}
