name: serverpod_lints_example
description: Demonstrates how to use the serverpod_lints package.
publish_to: none

environment:
  sdk: '>=2.19.0 <4.0.0'

dev_dependencies:
  serverpod_lints:
    path: ../