type: module
nickname: serverpod_auth_backwards_compatibility

modules:
  serverpod_auth_user:
    nickname: auth_user
  serverpod_auth_idp:
    nickname: auth_next

client_package_path: ../serverpod_auth_backwards_compatibility_client
server_test_tools_path: test/integration/test_tools
