name: serverpod_auth_user_server
version: 2.5.0
description: Starting point for a Serverpod module.

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  serverpod: 2.5.0

dev_dependencies:
  lints: '>=3.0.0 <6.0.0'
  test: '^1.24.2'
  serverpod_test: 2.5.0

