# Specify the Dart SDK base image version
FROM dart:3.8.0 AS build

# Set the working directory
WORKDIR /app

RUN echo "deb http://security.debian.org/debian-security bookworm-security main" >> /etc/apt/sources.list.d/debian.list \
    && apt-get update \
    && apt-get install --fix-missing -y xvfb firefox-esr \
    && rm -rf /var/lib/apt/lists/*

# Copy the whole serverpod repo into the container.
COPY . .

WORKDIR /app/tests/serverpod_test_server
RUN dart pub get

WORKDIR /app

# Setup database tables and start the server.
ENTRYPOINT ["tests/docker/tests_e2e/run-tests.sh"]
