name: serverpod_auth_backwards_compatibility_client
description: Serverpod authentication backwards compatibility client module.

environment:
  sdk: DART_VERSION

dependencies:
  serverpod_auth_email_account_client: SERVERPOD_VERSION
  serverpod_auth_user_client: SERVERPOD_VERSION
  serverpod_client: SERVERPOD_VERSION

dependency_overrides:
  serverpod_auth_email_account_client:
    path: ../../serverpod_auth_email_account/serverpod_auth_email_account_client
  serverpod_auth_user_client:
    path: ../../serverpod_auth_user/serverpod_auth_user_client
  serverpod_client:
    path: ../../../../packages/serverpod_client
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
