# TEMPLATE

name: serverpod_auth_bridge_client
description: Serverpod authentication backwards compatibility client module.
version: SERVERPOD_VERSION
repository: https://github.com/serverpod/serverpod

environment:
  sdk: DART_VERSION

resolution: workspace

dependencies:
  serverpod_auth_core_client: SERVERPOD_VERSION
  serverpod_auth_idp_client: SERVERPOD_VERSION
  serverpod_client: SERVERPOD_VERSION
