# TEMPLATE

name: serverpod_auth_idp_client
description: Client version of the next Serverpod authentication module.
version: SERVERPOD_VERSION
repository: https://github.com/serverpod/serverpod

environment:
  sdk: DART_VERSION

dependencies:
  serverpod_auth_profile_client: SERVERPOD_VERSION
  serverpod_auth_session_client: SERVERPOD_VERSION
  serverpod_auth_user_client: SERVERPOD_VERSION
  serverpod_client: SERVERPOD_VERSION

dependency_overrides:
  serverpod_auth_profile_client:
    path: ../../serverpod_auth_profile/serverpod_auth_profile_client
  serverpod_auth_session_client:
    path: ../../serverpod_auth_session/serverpod_auth_session_client
  serverpod_auth_user_client:
    path: ../../serverpod_auth_user/serverpod_auth_user_client
  serverpod_client:
    path: ../../../../packages/serverpod_client
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
