name: serverpod

packages:
  - examples/**
  - integrations/*
  - modules/**
  - packages/*
  - tests/**
  - tools/*
  - templates/serverpod_templates/*

categories:
  noTemplates:
    - examples/**
    - integrations/*
    - modules/**
    - packages/*
    - tests/**
    - tools/*

scripts:
  lint:
    run: melos analyze --fatal-warnings --category="noTemplates"
  lint_loose:
    run: melos analyze --no-fatal-warnings --category="noTemplates"
  lint_strict:
    run: melos analyze --fatal-infos --fatal-warnings --category="noTemplates"
  downgrade_flutter:
    run: melos exec --flutter --category="noTemplates" -c 1 -- flutter pub downgrade
  downgrade_dart:
    run: melos exec --no-flutter --category="noTemplates" -c 1 -- dart pub downgrade
  downgrade:
    run: melos downgrade_flutter && melos downgrade_dart
