name: serverpod_auth_profile_client
description: Serverpod authentication user profile client module.
version: 2.6.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  serverpod_client: 2.6.0

dependency_overrides:
  serverpod_client:
    path: ../../../../packages/serverpod_client
