name: serverpod_auth_migration_server
description: Starting point for a Serverpod module.

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  serverpod: 2.4.0
  serverpod_auth_server: 2.4.0
  serverpod_auth2_server: 2.4.0

dev_dependencies:
  lints: ">=3.0.0 <6.0.0"
  test: "^1.24.2"
  serverpod_test: 2.4.0

dependency_overrides:
  serverpod:
    path: ../../../../packages/serverpod
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
  serverpod_shared:
    path: ../../../../packages/serverpod_shared
  serverpod_test:
    path: ../../../../packages/serverpod_test
  serverpod_lints:
    path: ../../../../packages/serverpod_lints
  # This only has a dependency on the old auth module on purpose
  # The import from the new modules is based just on the shared function definitions / records,
  # so that a project that wants to migrate does not have to import all new endpoint packages.
  serverpod_auth_server:
    path: ../../../serverpod_auth/serverpod_auth_server
  serverpod_auth2_server:
    path: ../../serverpod_auth2/serverpod_auth2_server
