import 'dart:io';

import 'package:cli_tools/cli_tools.dart';
import 'package:path/path.dart' as p;
import 'package:serverpod_cli/src/config/config.dart';
import 'package:serverpod_cli/src/generator/analyzers.dart';
import 'package:serverpod_cli/src/util/serverpod_cli_logger.dart';
import 'package:serverpod_shared/serverpod_shared.dart';
import 'package:test/test.dart';

import '../../test_util/builders/generator_config_builder.dart';
import '../../test_util/endpoint_validation_helpers.dart';

const _firstOwner = 'first_project';
const _secondOwner = 'second_project';
const _sharedPackage = 'test_shared';

class _TestLogger extends VoidLogger {
  final errors = <String>[];

  @override
  void error(
    String message, {
    bool newParagraph = false,
    LogType? type,
    Object? exception,
    StackTrace? stackTrace,
  }) {
    errors.add(message);
  }
}

void main() {
  final testLogger = _TestLogger();

  setUpAll(() => initializeLoggerWith(testLogger));
  tearDownAll(closeLogger);

  group('Given a shared package generated by one project,', () {
    late Directory projectDir;
    late GeneratorConfig firstOwnerConfig;
    late GeneratorConfig secondOwnerConfig;
    late File generatedModelFile;
    late File generatedProtocolFile;
    late String firstOwnerModelContents;
    late String firstOwnerProtocolContents;

    tearDownAll(() => projectDir.deleteIfExists(recursive: true));

    setUp(() {
      testLogger.errors.clear();
      generatedModelFile.writeAsStringSync(firstOwnerModelContents);
      generatedProtocolFile.writeAsStringSync(firstOwnerProtocolContents);
    });

    setUpAll(() async {
      projectDir = Directory.systemTemp.createTempSync('cli_test_');
      final sharedDir = Directory(p.join(projectDir.path, _sharedPackage));

      await createTestEnvironment(projectDir);
      await _createSharedPackage(sharedDir);

      firstOwnerConfig = _buildConfig(
        projectDir,
        owner: _firstOwner,
      );
      secondOwnerConfig = _buildConfig(
        projectDir,
        owner: _secondOwner,
      );

      generatedModelFile = File(
        p.join(
          sharedDir.path,
          'lib',
          'src',
          'generated',
          'shared_model.dart',
        ),
      );
      generatedProtocolFile = File(
        p.join(
          sharedDir.path,
          'lib',
          'src',
          'generated',
          'protocol.dart',
        ),
      );

      final firstOwnerAnalyzers = await Analyzers.create(firstOwnerConfig);
      final firstResult = await firstOwnerAnalyzers.performGenerate(
        config: firstOwnerConfig,
      );

      expect(firstResult.success, isTrue);
      expect(firstResult.generatedFiles, isNotEmpty);
      firstOwnerModelContents = generatedModelFile.readAsStringSync();
      firstOwnerProtocolContents = generatedProtocolFile.readAsStringSync();
      expect(
        firstOwnerProtocolContents,
        contains("String getModuleName() => '$_firstOwner';"),
      );
    });

    test(
      'when another project generates it, then generation fails without '
      'overwriting its output.',
      () async {
        final secondOwnerAnalyzers = await Analyzers.create(secondOwnerConfig);
        final result = await secondOwnerAnalyzers.performGenerate(
          config: secondOwnerConfig,
        );

        expect(result.success, isFalse);
        expect(result.generatedFiles, isEmpty);
        expect(
          generatedModelFile.readAsStringSync(),
          firstOwnerModelContents,
        );
        expect(
          generatedProtocolFile.readAsStringSync(),
          firstOwnerProtocolContents,
        );
        expect(
          testLogger.errors.join('\n'),
          allOf(
            contains(_sharedPackage),
            contains(_firstOwner),
            contains(_secondOwner),
            contains('exactly one owner'),
            contains('Remove it from one project\'s shared_packages setting'),
          ),
        );
      },
    );

    test(
      'when the recorded owner generates it again, then generation succeeds.',
      () async {
        final firstOwnerAnalyzers = await Analyzers.create(firstOwnerConfig);
        final result = await firstOwnerAnalyzers.performGenerate(
          config: firstOwnerConfig,
        );

        expect(result.success, isTrue);
        expect(result.generatedFiles, isNotEmpty);
        expect(testLogger.errors, isEmpty);
      },
    );
  });
}

GeneratorConfig _buildConfig(
  Directory serverDir, {
  required String owner,
}) {
  return GeneratorConfigBuilder()
      .withName(owner)
      .withServerPackage('${owner}_server')
      .withDartClientPackage('${owner}_client')
      .withServerPackageDirectoryPathParts([serverDir.path])
      .withRelativeDartClientPackagePathParts(['${owner}_client'])
      .withSharedModelsSourcePathsParts({
        _sharedPackage: [_sharedPackage],
      })
      .withModules([
        ModuleConfig(
          type: PackageType.server,
          name: owner,
          nickname: owner,
          migrationVersions: [],
          serverPackageDirectoryPathParts: [serverDir.path],
        ),
      ])
      .build();
}

Future<void> _createSharedPackage(Directory sharedDir) async {
  final serverpodRoot = await resolveServerpodRoot();

  File(p.join(sharedDir.path, 'pubspec.yaml'))
    ..createSync(recursive: true)
    ..writeAsStringSync('''
name: $_sharedPackage

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serverpod_serialization:
    path: $serverpodRoot/packages/serverpod_serialization
''');

  File(
      p.join(
        sharedDir.path,
        'lib',
        'src',
        'models',
        'shared_model.spy.yaml',
      ),
    )
    ..createSync(recursive: true)
    ..writeAsStringSync('''
class: SharedModel
fields:
  name: String
''');
}
