name: serverpod_auth_email_client
description: Serverpod email authentication endpoint client module.
version: SERVERPOD_VERSION

environment:
  sdk: DART_VERSION

dependencies:
  serverpod_client: SERVERPOD_VERSION

dependency_overrides:
  serverpod_auth_email_account_client:
    path: ../../serverpod_auth_email_account/serverpod_auth_email_account_client
  serverpod_auth_profile_client:
    path: ../../serverpod_auth_profile/serverpod_auth_profile_client
  serverpod_auth_session_client:
    path: ../../serverpod_auth_session/serverpod_auth_session_client
  serverpod_auth_user_client:
    path: ../../serverpod_auth_user/serverpod_auth_user_client
  serverpod_client:
    path: ../../../../packages/serverpod_client
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
