import 'package:serverpod/serverpod.dart';

import 'email_idp_config.dart';
import 'util/serverpod_cloud_code_sender.dart';
import 'util/serverpod_cloud_email_client.dart';

export 'util/serverpod_cloud_email_client.dart';

/// {@template serverpod_cloud_email_idp_config}
/// An [EmailIdpConfig] that works with Serverpod Cloud without configuration.
///
/// In development and test run mode, verification codes are logged to the
/// console via [Session.alert] — the same behavior as the default development
/// setup. In staging and production run mode, emails are sent through the
/// hosted Serverpod Cloud transactional email service (see
/// [ServerpodCloudEmailClient]).
///
/// The staging/production setup reads the `scloudAuthEmailKey` password, which
/// is provided automatically by Serverpod Cloud. The key is read lazily when an
/// email is sent (not at startup), so a self-hosted server still boots when it
/// is unset. Sending is best-effort: a failure (outage, missing key, non-200,
/// or timeout) is logged and never propagated, so it neither breaks sign-up nor
/// reveals whether an account exists during password reset.
///
/// If you want to send emails through a custom provider instead, use
/// [EmailIdpConfigFromPasswords].
///
/// This requires that a [Serverpod] instance has already been initialized, as
/// it reads the `emailSecretHashPepper` password from the `passwords.yaml` file.
/// {@endtemplate}
class ServerpodCloudEmailIdpConfig extends EmailIdpConfigFromPasswords {
  /// {@macro serverpod_cloud_email_idp_config}
  ///
  /// [appDisplayName] is the name shown to recipients in the emails (at most 64
  /// characters) and is prefilled with the project name in the default
  /// template.
  ///
  /// The verification codes are generated by the default code generators (8
  /// lower-case alphanumeric characters). They must consist of 1–16 alphanumeric
  /// characters (`A-Z`, `a-z`, `0-9`) to be accepted by the email service.
  factory ServerpodCloudEmailIdpConfig({
    required final String appDisplayName,

    /// The client used to send emails in staging/production. Defaults to a
    /// [ServerpodCloudEmailClient] targeting the hosted service; override it to
    /// target a different endpoint or for testing.
    final ServerpodCloudEmailClient? emailClient,

    /// The run mode determining whether codes are logged (development/test) or
    /// emailed (staging/production). Defaults to `Serverpod.instance.runMode`;
    /// primarily an override for testing.
    final String? runMode,

    /// Callback to be invoked after a password reset is successfully completed.
    ///
    /// This can be used to perform additional cleanup tasks, such as clearing
    /// legacy passwords during migration scenarios.
    final OnPasswordResetCompletedFunction? onPasswordResetCompleted,

    /// Callback to be invoked after a new email account has been created.
    ///
    /// This can be used to perform additional setup tasks, such as creating a
    /// user profile or sending a welcome email.
    final AfterAccountCreatedFunction? onAfterAccountCreated,
  }) {
    final resolvedRunMode = runMode ?? Serverpod.instance.runMode;
    final isDevelopment =
        resolvedRunMode == ServerpodRunMode.development ||
        resolvedRunMode == ServerpodRunMode.test;

    // In development/test the codes are logged, so no HTTP client is needed.
    // Otherwise a single client is shared between both senders.
    final client = isDevelopment
        ? null
        : (emailClient ?? ServerpodCloudEmailClient());

    return ServerpodCloudEmailIdpConfig._(
      sendRegistrationVerificationCode: _registrationSender(
        serverpodCloudCodeSender(
          appDisplayName: appDisplayName,
          client: client,
          emailType: ServerpodCloudEmailType.signup,
          logLabel: 'Registration',
        ),
      ),
      sendPasswordResetVerificationCode: _passwordResetSender(
        serverpodCloudCodeSender(
          appDisplayName: appDisplayName,
          client: client,
          emailType: ServerpodCloudEmailType.lostpassword,
          logLabel: 'Password reset',
        ),
      ),
      onPasswordResetCompleted: onPasswordResetCompleted,
      onAfterAccountCreated: onAfterAccountCreated,
    );
  }

  // Reads `emailSecretHashPepper` via `EmailIdpConfigFromPasswords`.
  ServerpodCloudEmailIdpConfig._({
    required super.sendRegistrationVerificationCode,
    required super.sendPasswordResetVerificationCode,
    super.onPasswordResetCompleted,
    super.onAfterAccountCreated,
  });

  /// Adapts a shared [send] callback to the registration callback signature.
  static SendRegistrationVerificationCodeFunction _registrationSender(
    final SendCodeFunction send,
  ) {
    return (
      final Session session, {
      required final String email,
      required final UuidValue accountRequestId,
      required final String verificationCode,
      required final Transaction? transaction,
    }) => send(session, email: email, code: verificationCode);
  }

  /// Adapts a shared [send] callback to the password-reset callback signature.
  static SendPasswordResetVerificationCodeFunction _passwordResetSender(
    final SendCodeFunction send,
  ) {
    return (
      final Session session, {
      required final String email,
      required final UuidValue passwordResetRequestId,
      required final String verificationCode,
      required final Transaction? transaction,
    }) => send(session, email: email, code: verificationCode);
  }
}
