services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mytest
      POSTGRES_PASSWORD: "FoV3ZJTqigqX91ZNkoyZ2YgB6uE1DIhJ"
    volumes:
      - mytest_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "dhC3nxeZ9kMZVdTUxEatnyt5gnnPdIYB"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mytest_test
      POSTGRES_PASSWORD: "w0EXallJ30-25zhu14XNhiltz4SQm1Wq"
    volumes:
      - mytest_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "PedXEOdpjLBziivPet2m1EdTlYlTGNSW"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  mytest_data:
  mytest_test_data:
