/// AUTOGENERATED BY SERVERPOD create-migration - DO NOT EDIT BY HAND
/// Merging: resolve registry conflicts the same as migration_registry.txt.
library;

import 'package:serverpod_database/serverpod_database.dart';

part '20260425031610501/migration.dart';
part '20260620012700766/migration.dart';
part '20260625141124530/migration.dart';
part '20260708135909929/migration.dart';

/// Migration registry for the client-side database.
class MigrationRegistry {
  /// Ordered list of all client-side database migrations.
  /// New migrations are always appended at the end.
  static final List<MigrationVersionSql> migrations = [
    _Migration20260425031610501(),
    _Migration20260620012700766(),
    _Migration20260625141124530(),
    _Migration20260708135909929(),
  ];

  /// List of all client-side database migration versions.
  static List<String> get versions => migrations.map((m) => m.version).toList();
}
