name: serverpod_auth_session_flutter
description: Client-side companion for Serverpod servers using `serverpod_auth_session`.
version: 0.0.1
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  serverpod_auth_session_client: 2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  serverpod_lints: 2.9.0

dependency_overrides:
  serverpod_client:
    path: ../../../../packages/serverpod_client
  serverpod_auth_session_client:
    path: ../serverpod_auth_session_client
  serverpod_auth_user_client:
    path: ../../serverpod_auth_user/serverpod_auth_user_client
  serverpod_lints:
    path: ../../../../packages/serverpod_lints
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
