name: Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.8.0

      - name: Install dependencies
        working-directory: projectname_server
        run: dart pub get

      - name: Check formatting
        run: dart format --set-exit-if-changed .
