name: serverpod_auth_core_client
description: Serverpod core authentication client module.
version: 4.0.0-rc.1

environment:
  sdk: '^3.12.2'

resolution: workspace

dependencies:
  clock: ^1.1.1
  serverpod_client: 4.0.0-rc.1

dev_dependencies:
  test: ^1.25.5
