name: serverpod_auth_core_client
description: Serverpod core authentication client module.
version: 4.0.0-beta.1

environment:
  sdk: '^3.10.3'

resolution: workspace

dependencies:
  clock: ^1.1.1
  serverpod_client: 4.0.0-beta.1

dev_dependencies:
  test: ^1.25.5
