BEGIN;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "decimal_default" (
    "id" INTEGER PRIMARY KEY,
    "decimalDefault" TEXT NOT NULL DEFAULT ('10.5'),
    "decimalDefaultNull" TEXT DEFAULT ('20.5')
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "decimal_default_mix" (
    "id" INTEGER PRIMARY KEY,
    "decimalDefaultAndDefaultModel" TEXT NOT NULL DEFAULT ('10.5'),
    "decimalDefaultAndDefaultPersist" TEXT NOT NULL DEFAULT ('20.5'),
    "decimalDefaultModelAndDefaultPersist" TEXT NOT NULL DEFAULT ('20.5')
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "decimal_default_model" (
    "id" INTEGER PRIMARY KEY,
    "decimalDefaultModelStr" TEXT NOT NULL,
    "decimalDefaultModelStrNull" TEXT
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "decimal_default_persist" (
    "id" INTEGER PRIMARY KEY,
    "decimalDefaultPersist" TEXT DEFAULT ('10.5')
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "object_with_decimal" (
    "id" INTEGER PRIMARY KEY,
    "decimalValue" TEXT NOT NULL,
    "decimalValueNull" TEXT
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "object_with_decimal_precision" (
    "id" INTEGER PRIMARY KEY,
    "price" TEXT NOT NULL,
    "priceNullable" TEXT,
    "quantity" TEXT NOT NULL,
    "unbounded" TEXT NOT NULL,
    "priceWithDefault" TEXT NOT NULL DEFAULT ('9.99'),
    "priceWithDefaultNullable" TEXT DEFAULT ('1.23'),
    "quantityWithDefault" TEXT NOT NULL DEFAULT ('100.0000')
) STRICT;

--
-- STORE COLUMN TYPES FOR MIGRATIONS
--
DROP TABLE IF EXISTS "serverpod_sqlite_schema";

CREATE TABLE "serverpod_sqlite_schema" (
    "table_name" TEXT NOT NULL,
    "column_name" TEXT NOT NULL,
    "column_type" TEXT NOT NULL,
    "column_vector_dimension" INTEGER,
    "column_decimal_precision" INTEGER,
    "column_decimal_scale" INTEGER,
    PRIMARY KEY ("table_name", "column_name")
);

INSERT INTO "serverpod_sqlite_schema" VALUES
    ('address', 'id', 'bigint', NULL, NULL, NULL),
    ('address', 'street', 'text', NULL, NULL, NULL),
    ('address', 'inhabitantId', 'bigint', NULL, NULL, NULL),
    ('address_uuid', 'id', 'uuid', NULL, NULL, NULL),
    ('address_uuid', 'street', 'text', NULL, NULL, NULL),
    ('address_uuid', 'inhabitantId', 'bigint', NULL, NULL, NULL),
    ('arena', 'id', 'bigint', NULL, NULL, NULL),
    ('arena', 'name', 'text', NULL, NULL, NULL),
    ('arena_uuid', 'id', 'uuid', NULL, NULL, NULL),
    ('arena_uuid', 'name', 'text', NULL, NULL, NULL),
    ('bigint_default', 'id', 'bigint', NULL, NULL, NULL),
    ('bigint_default', 'bigintDefaultStr', 'text', NULL, NULL, NULL),
    ('bigint_default', 'bigintDefaultStrNull', 'text', NULL, NULL, NULL),
    ('bigint_default_mix', 'id', 'bigint', NULL, NULL, NULL),
    ('bigint_default_mix', 'bigIntDefaultAndDefaultModel', 'text', NULL, NULL, NULL),
    ('bigint_default_mix', 'bigIntDefaultAndDefaultPersist', 'text', NULL, NULL, NULL),
    ('bigint_default_mix', 'bigIntDefaultModelAndDefaultPersist', 'text', NULL, NULL, NULL),
    ('bigint_default_model', 'id', 'bigint', NULL, NULL, NULL),
    ('bigint_default_model', 'bigIntDefaultModelStr', 'text', NULL, NULL, NULL),
    ('bigint_default_model', 'bigIntDefaultModelStrNull', 'text', NULL, NULL, NULL),
    ('bigint_default_persist', 'id', 'bigint', NULL, NULL, NULL),
    ('bigint_default_persist', 'bigIntDefaultPersistStr', 'text', NULL, NULL, NULL),
    ('blocking', 'id', 'bigint', NULL, NULL, NULL),
    ('blocking', 'blockedId', 'bigint', NULL, NULL, NULL),
    ('blocking', 'blockedById', 'bigint', NULL, NULL, NULL),
    ('book', 'id', 'bigint', NULL, NULL, NULL),
    ('book', 'title', 'text', NULL, NULL, NULL),
    ('bool_default', 'id', 'bigint', NULL, NULL, NULL),
    ('bool_default', 'boolDefaultTrue', 'boolean', NULL, NULL, NULL),
    ('bool_default', 'boolDefaultFalse', 'boolean', NULL, NULL, NULL),
    ('bool_default', 'boolDefaultNullFalse', 'boolean', NULL, NULL, NULL),
    ('bool_default_mix', 'id', 'bigint', NULL, NULL, NULL),
    ('bool_default_mix', 'boolDefaultAndDefaultModel', 'boolean', NULL, NULL, NULL),
    ('bool_default_mix', 'boolDefaultAndDefaultPersist', 'boolean', NULL, NULL, NULL),
    ('bool_default_mix', 'boolDefaultModelAndDefaultPersist', 'boolean', NULL, NULL, NULL),
    ('bool_default_model', 'id', 'bigint', NULL, NULL, NULL),
    ('bool_default_model', 'boolDefaultModelTrue', 'boolean', NULL, NULL, NULL),
    ('bool_default_model', 'boolDefaultModelFalse', 'boolean', NULL, NULL, NULL),
    ('bool_default_model', 'boolDefaultModelNullFalse', 'boolean', NULL, NULL, NULL),
    ('bool_default_persist', 'id', 'bigint', NULL, NULL, NULL),
    ('bool_default_persist', 'boolDefaultPersistTrue', 'boolean', NULL, NULL, NULL),
    ('bool_default_persist', 'boolDefaultPersistFalse', 'boolean', NULL, NULL, NULL),
    ('cat', 'id', 'bigint', NULL, NULL, NULL),
    ('cat', 'name', 'text', NULL, NULL, NULL),
    ('cat', 'motherId', 'bigint', NULL, NULL, NULL),
    ('changed_id_type_self', 'id', 'uuid', NULL, NULL, NULL),
    ('changed_id_type_self', 'name', 'text', NULL, NULL, NULL),
    ('changed_id_type_self', 'nextId', 'uuid', NULL, NULL, NULL),
    ('changed_id_type_self', 'parentId', 'uuid', NULL, NULL, NULL),
    ('chapter', 'id', 'bigint', NULL, NULL, NULL),
    ('chapter', 'title', 'text', NULL, NULL, NULL),
    ('chapter', '_bookChaptersBookId', 'bigint', NULL, NULL, NULL),
    ('child_table_explicit_column', 'id', 'bigint', NULL, NULL, NULL),
    ('child_table_explicit_column', 'non_table_parent_field', 'text', NULL, NULL, NULL),
    ('child_table_explicit_column', 'child_field', 'text', NULL, NULL, NULL),
    ('citizen', 'id', 'bigint', NULL, NULL, NULL),
    ('citizen', 'name', 'text', NULL, NULL, NULL),
    ('citizen', 'companyId', 'bigint', NULL, NULL, NULL),
    ('citizen', 'oldCompanyId', 'bigint', NULL, NULL, NULL),
    ('citizen_int', 'id', 'bigint', NULL, NULL, NULL),
    ('citizen_int', 'name', 'text', NULL, NULL, NULL),
    ('citizen_int', 'companyId', 'uuid', NULL, NULL, NULL),
    ('citizen_int', 'oldCompanyId', 'uuid', NULL, NULL, NULL),
    ('city', 'id', 'bigint', NULL, NULL, NULL),
    ('city', 'name', 'text', NULL, NULL, NULL),
    ('city_with_long_table_name_that_is_still_valid', 'id', 'bigint', NULL, NULL, NULL),
    ('city_with_long_table_name_that_is_still_valid', 'name', 'text', NULL, NULL, NULL),
    ('comment', 'id', 'bigint', NULL, NULL, NULL),
    ('comment', 'description', 'text', NULL, NULL, NULL),
    ('comment', 'orderId', 'bigint', NULL, NULL, NULL),
    ('comment_int', 'id', 'bigint', NULL, NULL, NULL),
    ('comment_int', 'description', 'text', NULL, NULL, NULL),
    ('comment_int', 'orderId', 'uuid', NULL, NULL, NULL),
    ('company', 'id', 'bigint', NULL, NULL, NULL),
    ('company', 'name', 'text', NULL, NULL, NULL),
    ('company', 'townId', 'bigint', NULL, NULL, NULL),
    ('company_uuid', 'id', 'uuid', NULL, NULL, NULL),
    ('company_uuid', 'name', 'text', NULL, NULL, NULL),
    ('company_uuid', 'townId', 'bigint', NULL, NULL, NULL),
    ('contractor', 'id', 'bigint', NULL, NULL, NULL),
    ('contractor', 'name', 'text', NULL, NULL, NULL),
    ('contractor', 'fk_contractor_service_id', 'bigint', NULL, NULL, NULL),
    ('course', 'id', 'bigint', NULL, NULL, NULL),
    ('course', 'name', 'text', NULL, NULL, NULL),
    ('course_uuid', 'id', 'uuid', NULL, NULL, NULL),
    ('course_uuid', 'name', 'text', NULL, NULL, NULL),
    ('customer', 'id', 'bigint', NULL, NULL, NULL),
    ('customer', 'name', 'text', NULL, NULL, NULL),
    ('customer_int', 'id', 'bigint', NULL, NULL, NULL),
    ('customer_int', 'name', 'text', NULL, NULL, NULL),
    ('datetime_default', 'id', 'bigint', NULL, NULL, NULL),
    ('datetime_default', 'dateTimeDefaultNow', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('datetime_default', 'dateTimeDefaultStr', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('datetime_default', 'dateTimeDefaultStrNull', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('datetime_default_mix', 'id', 'bigint', NULL, NULL, NULL),
    ('datetime_default_mix', 'dateTimeDefaultAndDefaultModel', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('datetime_default_mix', 'dateTimeDefaultAndDefaultPersist', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('datetime_default_mix', 'dateTimeDefaultModelAndDefaultPersist', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('datetime_default_model', 'id', 'bigint', NULL, NULL, NULL),
    ('datetime_default_model', 'dateTimeDefaultModelNow', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('datetime_default_model', 'dateTimeDefaultModelStr', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('datetime_default_model', 'dateTimeDefaultModelStrNull', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('datetime_default_persist', 'id', 'bigint', NULL, NULL, NULL),
    ('datetime_default_persist', 'dateTimeDefaultPersistNow', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('datetime_default_persist', 'dateTimeDefaultPersistStr', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('decimal_default', 'id', 'bigint', NULL, NULL, NULL),
    ('decimal_default', 'decimalDefault', 'decimal', NULL, NULL, NULL),
    ('decimal_default', 'decimalDefaultNull', 'decimal', NULL, NULL, NULL),
    ('decimal_default_mix', 'id', 'bigint', NULL, NULL, NULL),
    ('decimal_default_mix', 'decimalDefaultAndDefaultModel', 'decimal', NULL, NULL, NULL),
    ('decimal_default_mix', 'decimalDefaultAndDefaultPersist', 'decimal', NULL, NULL, NULL),
    ('decimal_default_mix', 'decimalDefaultModelAndDefaultPersist', 'decimal', NULL, NULL, NULL),
    ('decimal_default_model', 'id', 'bigint', NULL, NULL, NULL),
    ('decimal_default_model', 'decimalDefaultModelStr', 'decimal', NULL, NULL, NULL),
    ('decimal_default_model', 'decimalDefaultModelStrNull', 'decimal', NULL, NULL, NULL),
    ('decimal_default_persist', 'id', 'bigint', NULL, NULL, NULL),
    ('decimal_default_persist', 'decimalDefaultPersist', 'decimal', NULL, NULL, NULL),
    ('department', 'id', 'bigint', NULL, NULL, NULL),
    ('department', 'name', 'text', NULL, NULL, NULL),
    ('double_default', 'id', 'bigint', NULL, NULL, NULL),
    ('double_default', 'doubleDefault', 'doublePrecision', NULL, NULL, NULL),
    ('double_default', 'doubleDefaultNull', 'doublePrecision', NULL, NULL, NULL),
    ('double_default_mix', 'id', 'bigint', NULL, NULL, NULL),
    ('double_default_mix', 'doubleDefaultAndDefaultModel', 'doublePrecision', NULL, NULL, NULL),
    ('double_default_mix', 'doubleDefaultAndDefaultPersist', 'doublePrecision', NULL, NULL, NULL),
    ('double_default_mix', 'doubleDefaultModelAndDefaultPersist', 'doublePrecision', NULL, NULL, NULL),
    ('double_default_model', 'id', 'bigint', NULL, NULL, NULL),
    ('double_default_model', 'doubleDefaultModel', 'doublePrecision', NULL, NULL, NULL),
    ('double_default_model', 'doubleDefaultModelNull', 'doublePrecision', NULL, NULL, NULL),
    ('double_default_persist', 'id', 'bigint', NULL, NULL, NULL),
    ('double_default_persist', 'doubleDefaultPersist', 'doublePrecision', NULL, NULL, NULL),
    ('duration_default', 'id', 'bigint', NULL, NULL, NULL),
    ('duration_default', 'durationDefault', 'bigint', NULL, NULL, NULL),
    ('duration_default', 'durationDefaultNull', 'bigint', NULL, NULL, NULL),
    ('duration_default_mix', 'id', 'bigint', NULL, NULL, NULL),
    ('duration_default_mix', 'durationDefaultAndDefaultModel', 'bigint', NULL, NULL, NULL),
    ('duration_default_mix', 'durationDefaultAndDefaultPersist', 'bigint', NULL, NULL, NULL),
    ('duration_default_mix', 'durationDefaultModelAndDefaultPersist', 'bigint', NULL, NULL, NULL),
    ('duration_default_model', 'id', 'bigint', NULL, NULL, NULL),
    ('duration_default_model', 'durationDefaultModel', 'bigint', NULL, NULL, NULL),
    ('duration_default_model', 'durationDefaultModelNull', 'bigint', NULL, NULL, NULL),
    ('duration_default_persist', 'id', 'bigint', NULL, NULL, NULL),
    ('duration_default_persist', 'durationDefaultPersist', 'bigint', NULL, NULL, NULL),
    ('employee', 'id', 'bigint', NULL, NULL, NULL),
    ('employee', 'name', 'text', NULL, NULL, NULL),
    ('employee', 'fk_employee_department_id', 'bigint', NULL, NULL, NULL),
    ('empty_model_relation_item', 'id', 'bigint', NULL, NULL, NULL),
    ('empty_model_relation_item', 'name', 'text', NULL, NULL, NULL),
    ('empty_model_relation_item', '_relationEmptyModelItemsRelationEmptyModelId', 'bigint', NULL, NULL, NULL),
    ('empty_model_with_table', 'id', 'bigint', NULL, NULL, NULL),
    ('enrollment', 'id', 'bigint', NULL, NULL, NULL),
    ('enrollment', 'studentId', 'bigint', NULL, NULL, NULL),
    ('enrollment', 'courseId', 'bigint', NULL, NULL, NULL),
    ('enrollment_int', 'id', 'bigint', NULL, NULL, NULL),
    ('enrollment_int', 'studentId', 'uuid', NULL, NULL, NULL),
    ('enrollment_int', 'courseId', 'uuid', NULL, NULL, NULL),
    ('enum_default', 'id', 'bigint', NULL, NULL, NULL),
    ('enum_default', 'byNameEnumDefault', 'text', NULL, NULL, NULL),
    ('enum_default', 'byNameEnumDefaultNull', 'text', NULL, NULL, NULL),
    ('enum_default', 'byIndexEnumDefault', 'bigint', NULL, NULL, NULL),
    ('enum_default', 'byIndexEnumDefaultNull', 'bigint', NULL, NULL, NULL),
    ('enum_default_mix', 'id', 'bigint', NULL, NULL, NULL),
    ('enum_default_mix', 'byNameEnumDefaultAndDefaultModel', 'text', NULL, NULL, NULL),
    ('enum_default_mix', 'byNameEnumDefaultAndDefaultPersist', 'text', NULL, NULL, NULL),
    ('enum_default_mix', 'byNameEnumDefaultModelAndDefaultPersist', 'text', NULL, NULL, NULL),
    ('enum_default_model', 'id', 'bigint', NULL, NULL, NULL),
    ('enum_default_model', 'byNameEnumDefaultModel', 'text', NULL, NULL, NULL),
    ('enum_default_model', 'byNameEnumDefaultModelNull', 'text', NULL, NULL, NULL),
    ('enum_default_model', 'byIndexEnumDefaultModel', 'bigint', NULL, NULL, NULL),
    ('enum_default_model', 'byIndexEnumDefaultModelNull', 'bigint', NULL, NULL, NULL),
    ('enum_default_persist', 'id', 'bigint', NULL, NULL, NULL),
    ('enum_default_persist', 'byNameEnumDefaultPersist', 'text', NULL, NULL, NULL),
    ('enum_default_persist', 'byIndexEnumDefaultPersist', 'bigint', NULL, NULL, NULL),
    ('int_default', 'id', 'bigint', NULL, NULL, NULL),
    ('int_default', 'intDefault', 'bigint', NULL, NULL, NULL),
    ('int_default', 'intDefaultNull', 'bigint', NULL, NULL, NULL),
    ('int_default_mix', 'id', 'bigint', NULL, NULL, NULL),
    ('int_default_mix', 'intDefaultAndDefaultModel', 'bigint', NULL, NULL, NULL),
    ('int_default_mix', 'intDefaultAndDefaultPersist', 'bigint', NULL, NULL, NULL),
    ('int_default_mix', 'intDefaultModelAndDefaultPersist', 'bigint', NULL, NULL, NULL),
    ('int_default_model', 'id', 'bigint', NULL, NULL, NULL),
    ('int_default_model', 'intDefaultModel', 'bigint', NULL, NULL, NULL),
    ('int_default_model', 'intDefaultModelNull', 'bigint', NULL, NULL, NULL),
    ('int_default_persist', 'id', 'bigint', NULL, NULL, NULL),
    ('int_default_persist', 'intDefaultPersist', 'bigint', NULL, NULL, NULL),
    ('long_implicit_id_field', 'id', 'bigint', NULL, NULL, NULL),
    ('long_implicit_id_field', 'name', 'text', NULL, NULL, NULL),
    ('long_implicit_id_field', '_longImplicitIdFieldCollectionThisfieldisexactly61charact0008Id', 'bigint', NULL, NULL, NULL),
    ('long_implicit_id_field_collection', 'id', 'bigint', NULL, NULL, NULL),
    ('long_implicit_id_field_collection', 'name', 'text', NULL, NULL, NULL),
    ('max_field_name', 'id', 'bigint', NULL, NULL, NULL),
    ('max_field_name', 'thisFieldIsExactly61CharactersLongAndIsThereforeValidAsNameFo', 'text', NULL, NULL, NULL),
    ('member', 'id', 'bigint', NULL, NULL, NULL),
    ('member', 'name', 'text', NULL, NULL, NULL),
    ('model_with_required_field', 'id', 'bigint', NULL, NULL, NULL),
    ('model_with_required_field', 'name', 'text', NULL, NULL, NULL),
    ('model_with_required_field', 'email', 'text', NULL, NULL, NULL),
    ('model_with_required_field', 'phone', 'text', NULL, NULL, NULL),
    ('modified_column_name', 'id', 'bigint', NULL, NULL, NULL),
    ('modified_column_name', 'originalColumn', 'text', NULL, NULL, NULL),
    ('modified_column_name', 'modified_column', 'text', NULL, NULL, NULL),
    ('multiple_max_field_name', 'id', 'bigint', NULL, NULL, NULL),
    ('multiple_max_field_name', 'thisFieldIsExactly61CharactersLongAndIsThereforeValidAsNames1', 'text', NULL, NULL, NULL),
    ('multiple_max_field_name', 'thisFieldIsExactly61CharactersLongAndIsThereforeValidAsNames2', 'text', NULL, NULL, NULL),
    ('multiple_max_field_name', '_relationToMultipleMaxFieldNameMultiplemaxfieldnamesRelat674eId', 'bigint', NULL, NULL, NULL),
    ('object_field_persist', 'id', 'bigint', NULL, NULL, NULL),
    ('object_field_persist', 'normal', 'text', NULL, NULL, NULL),
    ('object_field_scopes', 'id', 'bigint', NULL, NULL, NULL),
    ('object_field_scopes', 'normal', 'text', NULL, NULL, NULL),
    ('object_field_scopes', 'database', 'text', NULL, NULL, NULL),
    ('object_with_bit', 'id', 'bigint', NULL, NULL, NULL),
    ('object_with_bit', 'bit', 'bit', 512, NULL, NULL),
    ('object_with_bit', 'bitNullable', 'bit', 512, NULL, NULL),
    ('object_with_bit', 'bitIndexedHnsw', 'bit', 512, NULL, NULL),
    ('object_with_bit', 'bitIndexedHnswWithParams', 'bit', 512, NULL, NULL),
    ('object_with_bit', 'bitIndexedIvfflat', 'bit', 512, NULL, NULL),
    ('object_with_bit', 'bitIndexedIvfflatWithParams', 'bit', 512, NULL, NULL),
    ('object_with_bytedata', 'id', 'bigint', NULL, NULL, NULL),
    ('object_with_bytedata', 'byteData', 'bytea', NULL, NULL, NULL),
    ('object_with_decimal', 'id', 'bigint', NULL, NULL, NULL),
    ('object_with_decimal', 'decimalValue', 'decimal', NULL, NULL, NULL),
    ('object_with_decimal', 'decimalValueNull', 'decimal', NULL, NULL, NULL),
    ('object_with_decimal_precision', 'id', 'bigint', NULL, NULL, NULL),
    ('object_with_decimal_precision', 'price', 'decimal', NULL, 10, 2),
    ('object_with_decimal_precision', 'priceNullable', 'decimal', NULL, 10, 2),
    ('object_with_decimal_precision', 'quantity', 'decimal', NULL, 19, 4),
    ('object_with_decimal_precision', 'unbounded', 'decimal', NULL, NULL, NULL),
    ('object_with_decimal_precision', 'priceWithDefault', 'decimal', NULL, 10, 2),
    ('object_with_decimal_precision', 'priceWithDefaultNullable', 'decimal', NULL, 10, 2),
    ('object_with_decimal_precision', 'quantityWithDefault', 'decimal', NULL, 19, 4),
    ('object_with_duration', 'id', 'bigint', NULL, NULL, NULL),
    ('object_with_duration', 'duration', 'bigint', NULL, NULL, NULL),
    ('object_with_enum', 'id', 'bigint', NULL, NULL, NULL),
    ('object_with_enum', 'testEnum', 'bigint', NULL, NULL, NULL),
    ('object_with_enum', 'nullableEnum', 'bigint', NULL, NULL, NULL),
    ('object_with_enum', 'enumList', 'json', NULL, NULL, NULL),
    ('object_with_enum', 'nullableEnumList', 'json', NULL, NULL, NULL),
    ('object_with_enum', 'enumListList', 'json', NULL, NULL, NULL),
    ('object_with_enum_enhanced', 'id', 'bigint', NULL, NULL, NULL),
    ('object_with_enum_enhanced', 'byIndex', 'bigint', NULL, NULL, NULL),
    ('object_with_enum_enhanced', 'nullableByIndex', 'bigint', NULL, NULL, NULL),
    ('object_with_enum_enhanced', 'byIndexList', 'json', NULL, NULL, NULL),
    ('object_with_enum_enhanced', 'byName', 'text', NULL, NULL, NULL),
    ('object_with_enum_enhanced', 'nullableByName', 'text', NULL, NULL, NULL),
    ('object_with_enum_enhanced', 'byNameList', 'json', NULL, NULL, NULL),
    ('object_with_half_vector', 'id', 'bigint', NULL, NULL, NULL),
    ('object_with_half_vector', 'halfVector', 'halfvec', 512, NULL, NULL),
    ('object_with_half_vector', 'halfVectorNullable', 'halfvec', 512, NULL, NULL),
    ('object_with_half_vector', 'halfVectorIndexedHnsw', 'halfvec', 512, NULL, NULL),
    ('object_with_half_vector', 'halfVectorIndexedHnswWithParams', 'halfvec', 512, NULL, NULL),
    ('object_with_half_vector', 'halfVectorIndexedIvfflat', 'halfvec', 512, NULL, NULL),
    ('object_with_half_vector', 'halfVectorIndexedIvfflatWithParams', 'halfvec', 512, NULL, NULL),
    ('object_with_index', 'id', 'bigint', NULL, NULL, NULL),
    ('object_with_index', 'indexed', 'bigint', NULL, NULL, NULL),
    ('object_with_index', 'indexed2', 'bigint', NULL, NULL, NULL),
    ('object_with_object', 'id', 'bigint', NULL, NULL, NULL),
    ('object_with_object', 'data', 'json', NULL, NULL, NULL),
    ('object_with_object', 'nullableData', 'json', NULL, NULL, NULL),
    ('object_with_object', 'dataList', 'json', NULL, NULL, NULL),
    ('object_with_object', 'nullableDataList', 'json', NULL, NULL, NULL),
    ('object_with_object', 'listWithNullableData', 'json', NULL, NULL, NULL),
    ('object_with_object', 'nullableListWithNullableData', 'json', NULL, NULL, NULL),
    ('object_with_object', 'nestedDataList', 'json', NULL, NULL, NULL),
    ('object_with_object', 'nestedDataListInMap', 'json', NULL, NULL, NULL),
    ('object_with_object', 'nestedDataMap', 'json', NULL, NULL, NULL),
    ('object_with_parent', 'id', 'bigint', NULL, NULL, NULL),
    ('object_with_parent', 'other', 'bigint', NULL, NULL, NULL),
    ('object_with_self_parent', 'id', 'bigint', NULL, NULL, NULL),
    ('object_with_self_parent', 'other', 'bigint', NULL, NULL, NULL),
    ('object_with_sparse_vector', 'id', 'bigint', NULL, NULL, NULL),
    ('object_with_sparse_vector', 'sparseVector', 'sparsevec', 512, NULL, NULL),
    ('object_with_sparse_vector', 'sparseVectorNullable', 'sparsevec', 512, NULL, NULL),
    ('object_with_sparse_vector', 'sparseVectorIndexedHnsw', 'sparsevec', 512, NULL, NULL),
    ('object_with_sparse_vector', 'sparseVectorIndexedHnswWithParams', 'sparsevec', 512, NULL, NULL),
    ('object_with_uuid', 'id', 'bigint', NULL, NULL, NULL),
    ('object_with_uuid', 'uuid', 'uuid', NULL, NULL, NULL),
    ('object_with_uuid', 'uuidNullable', 'uuid', NULL, NULL, NULL),
    ('object_with_vector', 'id', 'bigint', NULL, NULL, NULL),
    ('object_with_vector', 'vector', 'vector', 512, NULL, NULL),
    ('object_with_vector', 'vectorNullable', 'vector', 512, NULL, NULL),
    ('object_with_vector', 'vectorIndexedHnsw', 'vector', 512, NULL, NULL),
    ('object_with_vector', 'vectorIndexedHnswWithParams', 'vector', 512, NULL, NULL),
    ('object_with_vector', 'vectorIndexedIvfflat', 'vector', 512, NULL, NULL),
    ('object_with_vector', 'vectorIndexedIvfflatWithParams', 'vector', 512, NULL, NULL),
    ('order', 'id', 'bigint', NULL, NULL, NULL),
    ('order', 'description', 'text', NULL, NULL, NULL),
    ('order', 'customerId', 'bigint', NULL, NULL, NULL),
    ('order_uuid', 'id', 'uuid', NULL, NULL, NULL),
    ('order_uuid', 'description', 'text', NULL, NULL, NULL),
    ('order_uuid', 'customerId', 'bigint', NULL, NULL, NULL),
    ('organization', 'id', 'bigint', NULL, NULL, NULL),
    ('organization', 'name', 'text', NULL, NULL, NULL),
    ('organization', 'cityId', 'bigint', NULL, NULL, NULL),
    ('organization_with_long_table_name_that_is_still_valid', 'id', 'bigint', NULL, NULL, NULL),
    ('organization_with_long_table_name_that_is_still_valid', 'name', 'text', NULL, NULL, NULL),
    ('organization_with_long_table_name_that_is_still_valid', 'cityId', 'bigint', NULL, NULL, NULL),
    ('person', 'id', 'bigint', NULL, NULL, NULL),
    ('person', 'name', 'text', NULL, NULL, NULL),
    ('person', 'organizationId', 'bigint', NULL, NULL, NULL),
    ('person', '_cityCitizensCityId', 'bigint', NULL, NULL, NULL),
    ('person_with_long_table_name_that_is_still_valid', 'id', 'bigint', NULL, NULL, NULL),
    ('person_with_long_table_name_that_is_still_valid', 'name', 'text', NULL, NULL, NULL),
    ('person_with_long_table_name_that_is_still_valid', 'organizationId', 'bigint', NULL, NULL, NULL),
    ('person_with_long_table_name_that_is_still_valid', '_cityWithLongTableNameThatIsStillValidCitizensCityWithLon4fe0Id', 'bigint', NULL, NULL, NULL),
    ('player', 'id', 'bigint', NULL, NULL, NULL),
    ('player', 'name', 'text', NULL, NULL, NULL),
    ('player', 'teamId', 'bigint', NULL, NULL, NULL),
    ('player_uuid', 'id', 'uuid', NULL, NULL, NULL),
    ('player_uuid', 'name', 'text', NULL, NULL, NULL),
    ('player_uuid', 'teamId', 'bigint', NULL, NULL, NULL),
    ('post', 'id', 'bigint', NULL, NULL, NULL),
    ('post', 'content', 'text', NULL, NULL, NULL),
    ('post', 'nextId', 'bigint', NULL, NULL, NULL),
    ('related_unique_data', 'id', 'bigint', NULL, NULL, NULL),
    ('related_unique_data', 'uniqueDataId', 'bigint', NULL, NULL, NULL),
    ('related_unique_data', 'number', 'bigint', NULL, NULL, NULL),
    ('relation_empty_model', 'id', 'bigint', NULL, NULL, NULL),
    ('relation_to_multiple_max_field_name', 'id', 'bigint', NULL, NULL, NULL),
    ('relation_to_multiple_max_field_name', 'name', 'text', NULL, NULL, NULL),
    ('server_only_changed_id_field_class', 'id', 'uuid', NULL, NULL, NULL),
    ('service', 'id', 'bigint', NULL, NULL, NULL),
    ('service', 'name', 'text', NULL, NULL, NULL),
    ('service', 'description', 'text', NULL, NULL, NULL),
    ('simple_data', 'id', 'bigint', NULL, NULL, NULL),
    ('simple_data', 'num', 'bigint', NULL, NULL, NULL),
    ('simple_date_time', 'id', 'bigint', NULL, NULL, NULL),
    ('simple_date_time', 'dateTime', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('string_default', 'id', 'bigint', NULL, NULL, NULL),
    ('string_default', 'stringDefault', 'text', NULL, NULL, NULL),
    ('string_default', 'stringDefaultNull', 'text', NULL, NULL, NULL),
    ('string_default_mix', 'id', 'bigint', NULL, NULL, NULL),
    ('string_default_mix', 'stringDefaultAndDefaultModel', 'text', NULL, NULL, NULL),
    ('string_default_mix', 'stringDefaultAndDefaultPersist', 'text', NULL, NULL, NULL),
    ('string_default_mix', 'stringDefaultModelAndDefaultPersist', 'text', NULL, NULL, NULL),
    ('string_default_model', 'id', 'bigint', NULL, NULL, NULL),
    ('string_default_model', 'stringDefaultModel', 'text', NULL, NULL, NULL),
    ('string_default_model', 'stringDefaultModelNull', 'text', NULL, NULL, NULL),
    ('string_default_persist', 'id', 'bigint', NULL, NULL, NULL),
    ('string_default_persist', 'stringDefaultPersist', 'text', NULL, NULL, NULL),
    ('string_default_persist', 'stringDefaultPersistSingleQuoteWithOneSingleEscapeQuote', 'text', NULL, NULL, NULL),
    ('string_default_persist', 'stringDefaultPersistSingleQuoteWithTwoSingleEscapeQuote', 'text', NULL, NULL, NULL),
    ('string_default_persist', 'stringDefaultPersistDoubleQuoteWithOneDoubleEscapeQuote', 'text', NULL, NULL, NULL),
    ('string_default_persist', 'stringDefaultPersistDoubleQuoteWithTwoDoubleEscapeQuote', 'text', NULL, NULL, NULL),
    ('string_default_persist', 'stringDefaultPersistSingleQuoteWithOneDoubleQuote', 'text', NULL, NULL, NULL),
    ('string_default_persist', 'stringDefaultPersistSingleQuoteWithTwoDoubleQuote', 'text', NULL, NULL, NULL),
    ('string_default_persist', 'stringDefaultPersistDoubleQuoteWithOneSingleQuote', 'text', NULL, NULL, NULL),
    ('string_default_persist', 'stringDefaultPersistDoubleQuoteWithTwoSingleQuote', 'text', NULL, NULL, NULL),
    ('student', 'id', 'bigint', NULL, NULL, NULL),
    ('student', 'name', 'text', NULL, NULL, NULL),
    ('student_uuid', 'id', 'uuid', NULL, NULL, NULL),
    ('student_uuid', 'name', 'text', NULL, NULL, NULL),
    ('table_with_explicit_column_names', 'id', 'bigint', NULL, NULL, NULL),
    ('table_with_explicit_column_names', 'user_name', 'text', NULL, NULL, NULL),
    ('table_with_explicit_column_names', 'user_description', 'text', NULL, NULL, NULL),
    ('team', 'id', 'bigint', NULL, NULL, NULL),
    ('team', 'name', 'text', NULL, NULL, NULL),
    ('team', 'arenaId', 'bigint', NULL, NULL, NULL),
    ('team_int', 'id', 'bigint', NULL, NULL, NULL),
    ('team_int', 'name', 'text', NULL, NULL, NULL),
    ('team_int', 'arenaId', 'uuid', NULL, NULL, NULL),
    ('town', 'id', 'bigint', NULL, NULL, NULL),
    ('town', 'name', 'text', NULL, NULL, NULL),
    ('town', 'mayorId', 'bigint', NULL, NULL, NULL),
    ('town_int', 'id', 'bigint', NULL, NULL, NULL),
    ('town_int', 'name', 'text', NULL, NULL, NULL),
    ('town_int', 'mayorId', 'bigint', NULL, NULL, NULL),
    ('types', 'id', 'bigint', NULL, NULL, NULL),
    ('types', 'anInt', 'bigint', NULL, NULL, NULL),
    ('types', 'aBool', 'boolean', NULL, NULL, NULL),
    ('types', 'aDouble', 'doublePrecision', NULL, NULL, NULL),
    ('types', 'aDateTime', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('types', 'aString', 'text', NULL, NULL, NULL),
    ('types', 'aByteData', 'bytea', NULL, NULL, NULL),
    ('types', 'aDuration', 'bigint', NULL, NULL, NULL),
    ('types', 'aUuid', 'uuid', NULL, NULL, NULL),
    ('types', 'aUri', 'text', NULL, NULL, NULL),
    ('types', 'aBigInt', 'text', NULL, NULL, NULL),
    ('types', 'aVector', 'vector', 3, NULL, NULL),
    ('types', 'aHalfVector', 'halfvec', 3, NULL, NULL),
    ('types', 'aSparseVector', 'sparsevec', 3, NULL, NULL),
    ('types', 'aBit', 'bit', 3, NULL, NULL),
    ('types', 'anEnum', 'bigint', NULL, NULL, NULL),
    ('types', 'aStringifiedEnum', 'text', NULL, NULL, NULL),
    ('types', 'aList', 'json', NULL, NULL, NULL),
    ('types', 'aMap', 'json', NULL, NULL, NULL),
    ('types', 'aSet', 'json', NULL, NULL, NULL),
    ('types', 'aRecord', 'json', NULL, NULL, NULL),
    ('unique_data', 'id', 'bigint', NULL, NULL, NULL),
    ('unique_data', 'number', 'bigint', NULL, NULL, NULL),
    ('unique_data', 'email', 'text', NULL, NULL, NULL),
    ('unique_data_with_non_persist', 'id', 'bigint', NULL, NULL, NULL),
    ('unique_data_with_non_persist', 'number', 'bigint', NULL, NULL, NULL),
    ('unique_data_with_non_persist', 'email', 'text', NULL, NULL, NULL),
    ('uri_default', 'id', 'bigint', NULL, NULL, NULL),
    ('uri_default', 'uriDefault', 'text', NULL, NULL, NULL),
    ('uri_default', 'uriDefaultNull', 'text', NULL, NULL, NULL),
    ('uri_default_mix', 'id', 'bigint', NULL, NULL, NULL),
    ('uri_default_mix', 'uriDefaultAndDefaultModel', 'text', NULL, NULL, NULL),
    ('uri_default_mix', 'uriDefaultAndDefaultPersist', 'text', NULL, NULL, NULL),
    ('uri_default_mix', 'uriDefaultModelAndDefaultPersist', 'text', NULL, NULL, NULL),
    ('uri_default_model', 'id', 'bigint', NULL, NULL, NULL),
    ('uri_default_model', 'uriDefaultModel', 'text', NULL, NULL, NULL),
    ('uri_default_model', 'uriDefaultModelNull', 'text', NULL, NULL, NULL),
    ('uri_default_persist', 'id', 'bigint', NULL, NULL, NULL),
    ('uri_default_persist', 'uriDefaultPersist', 'text', NULL, NULL, NULL),
    ('user_note', 'id', 'bigint', NULL, NULL, NULL),
    ('user_note', 'name', 'text', NULL, NULL, NULL),
    ('user_note', '_userNoteCollectionsUsernotespropertynameUserNoteCollectionsId', 'bigint', NULL, NULL, NULL),
    ('user_note_collection_with_a_long_name', 'id', 'bigint', NULL, NULL, NULL),
    ('user_note_collection_with_a_long_name', 'name', 'text', NULL, NULL, NULL),
    ('user_note_collections', 'id', 'bigint', NULL, NULL, NULL),
    ('user_note_collections', 'name', 'text', NULL, NULL, NULL),
    ('user_note_with_a_long_name', 'id', 'bigint', NULL, NULL, NULL),
    ('user_note_with_a_long_name', 'name', 'text', NULL, NULL, NULL),
    ('user_note_with_a_long_name', '_userNoteCollectionWithALongNameNotesUserNoteCollectionWi06adId', 'bigint', NULL, NULL, NULL),
    ('uuid_default', 'id', 'bigint', NULL, NULL, NULL),
    ('uuid_default', 'uuidDefaultRandom', 'uuid', NULL, NULL, NULL),
    ('uuid_default', 'uuidDefaultRandomV7', 'uuid', NULL, NULL, NULL),
    ('uuid_default', 'uuidDefaultRandomNull', 'uuid', NULL, NULL, NULL),
    ('uuid_default', 'uuidDefaultStr', 'uuid', NULL, NULL, NULL),
    ('uuid_default', 'uuidDefaultStrNull', 'uuid', NULL, NULL, NULL),
    ('uuid_default_mix', 'id', 'bigint', NULL, NULL, NULL),
    ('uuid_default_mix', 'uuidDefaultAndDefaultModel', 'uuid', NULL, NULL, NULL),
    ('uuid_default_mix', 'uuidDefaultAndDefaultPersist', 'uuid', NULL, NULL, NULL),
    ('uuid_default_mix', 'uuidDefaultModelAndDefaultPersist', 'uuid', NULL, NULL, NULL),
    ('uuid_default_model', 'id', 'bigint', NULL, NULL, NULL),
    ('uuid_default_model', 'uuidDefaultModelRandom', 'uuid', NULL, NULL, NULL),
    ('uuid_default_model', 'uuidDefaultModelRandomV7', 'uuid', NULL, NULL, NULL),
    ('uuid_default_model', 'uuidDefaultModelRandomNull', 'uuid', NULL, NULL, NULL),
    ('uuid_default_model', 'uuidDefaultModelStr', 'uuid', NULL, NULL, NULL),
    ('uuid_default_model', 'uuidDefaultModelStrNull', 'uuid', NULL, NULL, NULL),
    ('uuid_default_persist', 'id', 'bigint', NULL, NULL, NULL),
    ('uuid_default_persist', 'uuidDefaultPersistRandom', 'uuid', NULL, NULL, NULL),
    ('uuid_default_persist', 'uuidDefaultPersistRandomV7', 'uuid', NULL, NULL, NULL),
    ('uuid_default_persist', 'uuidDefaultPersistStr', 'uuid', NULL, NULL, NULL),
    ('serverpod_cloud_storage', 'id', 'bigint', NULL, NULL, NULL),
    ('serverpod_cloud_storage', 'storageId', 'text', NULL, NULL, NULL),
    ('serverpod_cloud_storage', 'path', 'text', NULL, NULL, NULL),
    ('serverpod_cloud_storage', 'addedTime', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('serverpod_cloud_storage', 'expiration', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('serverpod_cloud_storage', 'byteData', 'bytea', NULL, NULL, NULL),
    ('serverpod_cloud_storage', 'verified', 'boolean', NULL, NULL, NULL),
    ('serverpod_cloud_storage_direct_upload', 'id', 'bigint', NULL, NULL, NULL),
    ('serverpod_cloud_storage_direct_upload', 'storageId', 'text', NULL, NULL, NULL),
    ('serverpod_cloud_storage_direct_upload', 'path', 'text', NULL, NULL, NULL),
    ('serverpod_cloud_storage_direct_upload', 'expiration', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('serverpod_cloud_storage_direct_upload', 'authKey', 'text', NULL, NULL, NULL),
    ('serverpod_future_call', 'id', 'bigint', NULL, NULL, NULL),
    ('serverpod_future_call', 'name', 'text', NULL, NULL, NULL),
    ('serverpod_future_call', 'time', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('serverpod_future_call', 'serializedObject', 'text', NULL, NULL, NULL),
    ('serverpod_future_call', 'serverId', 'text', NULL, NULL, NULL),
    ('serverpod_future_call', 'identifier', 'text', NULL, NULL, NULL),
    ('serverpod_future_call', 'scheduling', 'json', NULL, NULL, NULL),
    ('serverpod_future_call_claim', 'id', 'bigint', NULL, NULL, NULL),
    ('serverpod_future_call_claim', 'futureCallId', 'bigint', NULL, NULL, NULL),
    ('serverpod_future_call_claim', 'lastHeartbeatTime', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('serverpod_health_connection_info', 'id', 'bigint', NULL, NULL, NULL),
    ('serverpod_health_connection_info', 'serverId', 'text', NULL, NULL, NULL),
    ('serverpod_health_connection_info', 'timestamp', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('serverpod_health_connection_info', 'active', 'bigint', NULL, NULL, NULL),
    ('serverpod_health_connection_info', 'closing', 'bigint', NULL, NULL, NULL),
    ('serverpod_health_connection_info', 'idle', 'bigint', NULL, NULL, NULL),
    ('serverpod_health_connection_info', 'granularity', 'bigint', NULL, NULL, NULL),
    ('serverpod_health_metric', 'id', 'bigint', NULL, NULL, NULL),
    ('serverpod_health_metric', 'name', 'text', NULL, NULL, NULL),
    ('serverpod_health_metric', 'serverId', 'text', NULL, NULL, NULL),
    ('serverpod_health_metric', 'timestamp', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('serverpod_health_metric', 'isHealthy', 'boolean', NULL, NULL, NULL),
    ('serverpod_health_metric', 'value', 'doublePrecision', NULL, NULL, NULL),
    ('serverpod_health_metric', 'granularity', 'bigint', NULL, NULL, NULL),
    ('serverpod_log', 'id', 'bigint', NULL, NULL, NULL),
    ('serverpod_log', 'sessionLogId', 'bigint', NULL, NULL, NULL),
    ('serverpod_log', 'messageId', 'bigint', NULL, NULL, NULL),
    ('serverpod_log', 'reference', 'text', NULL, NULL, NULL),
    ('serverpod_log', 'serverId', 'text', NULL, NULL, NULL),
    ('serverpod_log', 'time', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('serverpod_log', 'logLevel', 'bigint', NULL, NULL, NULL),
    ('serverpod_log', 'message', 'text', NULL, NULL, NULL),
    ('serverpod_log', 'error', 'text', NULL, NULL, NULL),
    ('serverpod_log', 'stackTrace', 'text', NULL, NULL, NULL),
    ('serverpod_log', 'order', 'bigint', NULL, NULL, NULL),
    ('serverpod_message_log', 'id', 'bigint', NULL, NULL, NULL),
    ('serverpod_message_log', 'sessionLogId', 'bigint', NULL, NULL, NULL),
    ('serverpod_message_log', 'serverId', 'text', NULL, NULL, NULL),
    ('serverpod_message_log', 'messageId', 'bigint', NULL, NULL, NULL),
    ('serverpod_message_log', 'endpoint', 'text', NULL, NULL, NULL),
    ('serverpod_message_log', 'messageName', 'text', NULL, NULL, NULL),
    ('serverpod_message_log', 'duration', 'doublePrecision', NULL, NULL, NULL),
    ('serverpod_message_log', 'error', 'text', NULL, NULL, NULL),
    ('serverpod_message_log', 'stackTrace', 'text', NULL, NULL, NULL),
    ('serverpod_message_log', 'slow', 'boolean', NULL, NULL, NULL),
    ('serverpod_message_log', 'order', 'bigint', NULL, NULL, NULL),
    ('serverpod_method', 'id', 'bigint', NULL, NULL, NULL),
    ('serverpod_method', 'endpoint', 'text', NULL, NULL, NULL),
    ('serverpod_method', 'method', 'text', NULL, NULL, NULL),
    ('serverpod_migrations', 'id', 'bigint', NULL, NULL, NULL),
    ('serverpod_migrations', 'module', 'text', NULL, NULL, NULL),
    ('serverpod_migrations', 'version', 'text', NULL, NULL, NULL),
    ('serverpod_migrations', 'timestamp', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('serverpod_query_log', 'id', 'bigint', NULL, NULL, NULL),
    ('serverpod_query_log', 'serverId', 'text', NULL, NULL, NULL),
    ('serverpod_query_log', 'sessionLogId', 'bigint', NULL, NULL, NULL),
    ('serverpod_query_log', 'messageId', 'bigint', NULL, NULL, NULL),
    ('serverpod_query_log', 'query', 'text', NULL, NULL, NULL),
    ('serverpod_query_log', 'duration', 'doublePrecision', NULL, NULL, NULL),
    ('serverpod_query_log', 'numRows', 'bigint', NULL, NULL, NULL),
    ('serverpod_query_log', 'error', 'text', NULL, NULL, NULL),
    ('serverpod_query_log', 'stackTrace', 'text', NULL, NULL, NULL),
    ('serverpod_query_log', 'slow', 'boolean', NULL, NULL, NULL),
    ('serverpod_query_log', 'order', 'bigint', NULL, NULL, NULL),
    ('serverpod_readwrite_test', 'id', 'bigint', NULL, NULL, NULL),
    ('serverpod_readwrite_test', 'number', 'bigint', NULL, NULL, NULL),
    ('serverpod_runtime_settings', 'id', 'bigint', NULL, NULL, NULL),
    ('serverpod_runtime_settings', 'logSettings', 'json', NULL, NULL, NULL),
    ('serverpod_runtime_settings', 'logSettingsOverrides', 'json', NULL, NULL, NULL),
    ('serverpod_runtime_settings', 'logServiceCalls', 'boolean', NULL, NULL, NULL),
    ('serverpod_runtime_settings', 'logMalformedCalls', 'boolean', NULL, NULL, NULL),
    ('serverpod_session_log', 'id', 'bigint', NULL, NULL, NULL),
    ('serverpod_session_log', 'serverId', 'text', NULL, NULL, NULL),
    ('serverpod_session_log', 'time', 'timestampWithoutTimeZone', NULL, NULL, NULL),
    ('serverpod_session_log', 'module', 'text', NULL, NULL, NULL),
    ('serverpod_session_log', 'endpoint', 'text', NULL, NULL, NULL),
    ('serverpod_session_log', 'method', 'text', NULL, NULL, NULL),
    ('serverpod_session_log', 'duration', 'doublePrecision', NULL, NULL, NULL),
    ('serverpod_session_log', 'numQueries', 'bigint', NULL, NULL, NULL),
    ('serverpod_session_log', 'slow', 'boolean', NULL, NULL, NULL),
    ('serverpod_session_log', 'error', 'text', NULL, NULL, NULL),
    ('serverpod_session_log', 'stackTrace', 'text', NULL, NULL, NULL),
    ('serverpod_session_log', 'authenticatedUserId', 'bigint', NULL, NULL, NULL),
    ('serverpod_session_log', 'userId', 'text', NULL, NULL, NULL),
    ('serverpod_session_log', 'isOpen', 'boolean', NULL, NULL, NULL),
    ('serverpod_session_log', 'touched', 'timestampWithoutTimeZone', NULL, NULL, NULL);

--
-- MIGRATION VERSION FOR serverpod_test_sqlite
--
INSERT INTO "serverpod_migrations" ("module", "version", "timestamp")
    VALUES ('serverpod_test_sqlite', '20260419104014323', (unixepoch('now', 'subsecond') * 1000))
    ON CONFLICT ("module")
    DO UPDATE SET "version" = '20260419104014323', "timestamp" = (unixepoch('now', 'subsecond') * 1000);

--
-- MIGRATION VERSION FOR serverpod
--
INSERT INTO "serverpod_migrations" ("module", "version", "timestamp")
    VALUES ('serverpod', '20260416151914983-insights-perf', (unixepoch('now', 'subsecond') * 1000))
    ON CONFLICT ("module")
    DO UPDATE SET "version" = '20260416151914983-insights-perf', "timestamp" = (unixepoch('now', 'subsecond') * 1000);


COMMIT;
