# TEMPLATE

name: serverpod_auth_google_account_server
description: Serverpod Google authentication core server module.
version: SERVERPOD_VERSION
repository: https://github.com/serverpod/serverpod

environment:
  sdk: DART_VERSION

dependencies:
  googleapis: ">=11.0.0 <15.0.0"
  googleapis_auth: ">=1.6.0 <3.0.0"
  http: ">=1.1.0 <2.0.0"
  meta: ^1.11.0
  serverpod: SERVERPOD_VERSION
  serverpod_auth_user_server: SERVERPOD_VERSION
  serverpod_shared: SERVERPOD_VERSION

dev_dependencies:
  serverpod_lints: SERVERPOD_VERSION
  serverpod_test: SERVERPOD_VERSION
  test: ^1.24.2

dependency_overrides:
  serverpod:
    path: ../../../../packages/serverpod
  serverpod_auth_user_server:
    path: ../../serverpod_auth_user/serverpod_auth_user_server
  serverpod_lints:
    path: ../../../../packages/serverpod_lints
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
  serverpod_shared:
    path: ../../../../packages/serverpod_shared
  serverpod_test:
    path: ../../../../packages/serverpod_test
