name: serverpod_auth_bridge_flutter
description: Serverpod authentication backwards compatibility Flutter client module.

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  serverpod_auth_core_client: 3.0.0-alpha.1
  serverpod_auth_core_flutter: 3.0.0-alpha.1
  serverpod_auth_bridge_client: 3.0.0-alpha.1
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  serverpod_lints: 3.0.0-alpha.1

dependency_overrides:
  serverpod_client:
    path: ../../../../packages/serverpod_client
  serverpod_auth_bridge_client:
    path: ../serverpod_auth_bridge_client
  serverpod_auth_idp_client:
    path: ../../serverpod_auth_idp/serverpod_auth_idp_client
  serverpod_auth_core_client:
    path: ../../serverpod_auth_core/serverpod_auth_core_client
  serverpod_auth_core_flutter:
    path: ../../serverpod_auth_core/serverpod_auth_core_flutter
  serverpod_lints:
    path: ../../../../packages/serverpod_lints
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
