# TEMPLATE

name: serverpod_push_store_flutter_firebase
description: Firebase Cloud Messaging integration for the Serverpod push Flutter registrar.
version: SERVERPOD_VERSION
repository: https://github.com/serverpod/serverpod

environment:
  sdk: DART_VERSION
  flutter: FLUTTER_VERSION

resolution: workspace

dependencies:
  firebase_messaging: ^16.0.0
  flutter:
    sdk: flutter
  meta: ^1.15.0
  serverpod_push_core_client: SERVERPOD_VERSION
  serverpod_push_store_client: SERVERPOD_VERSION
  serverpod_push_store_flutter: SERVERPOD_VERSION

dev_dependencies:
  flutter_test:
    sdk: flutter
  serverpod_lints: SERVERPOD_VERSION
