include: package:serverpod_lints/public_flutter.yaml

linter:
  rules:
    unawaited_futures: true
    discarded_futures: true
    prefer_initializing_formals: false

formatter:
  trailing_commas: preserve
