#!/usr/bin/env bash
# Writes pubspec_overrides.yaml listing only Dart-only workspace packages.
# Used by the composite action (standalone Dart SDK CI) and Dockerfile-server.
set -euo pipefail

workspace_root="${1:-.}"
workspace_root="$(cd "$workspace_root" && pwd)"
root_pubspec="$workspace_root/pubspec.yaml"
override="$workspace_root/pubspec_overrides.yaml"

if [ ! -f "$root_pubspec" ]; then
  echo "No pubspec.yaml in $workspace_root" >&2
  exit 1
fi

shopt -s nullglob

{
  echo "# Generated by .github/actions/use-dart-only-workspace."
  echo "workspace:"
  awk '
    /^workspace:[[:space:]]*$/ { in_workspace = 1; next }
    in_workspace && /^  - / {
      sub(/^  - /, "")
      print
      next
    }
    in_workspace && /^[^[:space:]]/ { exit }
  ' "$root_pubspec" | while IFS= read -r pattern; do
    [ -z "$pattern" ] && continue
    for match in "$workspace_root"/$pattern; do
      package_pubspec="$match/pubspec.yaml"
      if [ ! -f "$package_pubspec" ]; then
        continue
      fi
      if grep -Eq '^[[:space:]]+sdk:[[:space:]]+flutter([[:space:]]*(#.*)?)?$' "$package_pubspec"; then
        continue
      fi
      printf '  - %s\n' "${match#"$workspace_root"/}"
    done
  done
} > "$override"
