# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# Save passwords used across all configurations here.
shared:
  mySharedPassword: 'my password'

# These are passwords used when running the server locally in development mode
development:
  database: 'DB_PASSWORD'
  redis: 'REDIS_PASSWORD'

  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: 'SERVICE_SECRET_DEVELOPMENT'

# Passwords used in your staging environment if you use one.
staging:
  database: 'my database password'
  redis: 'my redis password'
  serviceSecret: 'SERVICE_SECRET_STAGING'

# Passwords used in production mode.
production:
  database: 'my database password'
  redis: 'my redis password'
  serviceSecret: 'SERVICE_SECRET_PRODUCTION'
