name: serverpod_auth_apple_client
description: Serverpod Sign in with Apple authentication endpoint client module.
version: 2.9.1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  serverpod_auth_apple_account_client: 2.9.1
  serverpod_auth_profile_client: 2.9.1
  serverpod_auth_session_client: 2.9.1
  serverpod_auth_user_client: 2.9.1
  serverpod_client: 2.9.1

dependency_overrides:
  serverpod_auth_apple_account_client:
    path: ../../serverpod_auth_apple_account/serverpod_auth_apple_account_client
  serverpod_auth_profile_client:
    path: ../../serverpod_auth_profile/serverpod_auth_profile_client
  serverpod_auth_session_client:
    path: ../../serverpod_auth_session/serverpod_auth_session_client
  serverpod_auth_user_client:
    path: ../../serverpod_auth_user/serverpod_auth_user_client
  serverpod_client:
    path: ../../../../packages/serverpod_client
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
