# Specify the Dart SDK base image version
FROM dart:2.19 AS build

# Set the working directory
WORKDIR /app

# Copy the whole serverpod repo into the container.
COPY . .

# Setup database tables and start the server.
CMD ["tests/docker/tests_single_server/run-tests.sh"]
