import 'dart:io';

import 'package:serverpod_database/serverpod_database.dart';
import 'package:test/test.dart';
import 'package:test_descriptor/test_descriptor.dart' as d;

const _migrationRegistryHeader = '''
### AUTOMATICALLY GENERATED DO NOT MODIFY
###
### This file is generated by Serverpod when creating a migration, do not modify it
### manually. If a collision is detected in this file when doing a code merge, resolve
### the conflict by removing and recreating the conflicting migration.

''';

void main() {
  group(
    'Given a file system migration artifact store where the last migration '
    'version directory is empty,',
    () {
      late FileSystemMigrationArtifactStore artifactStore;

      setUp(() async {
        await d.dir('migrations', [
          d.file(
            'migration_registry.txt',
            '${_migrationRegistryHeader}10000000000000\n20000000000000\n',
          ),
          d.dir('10000000000000', [d.file('definition.json', '{}')]),
          d.dir('20000000000000'),
        ]).create();

        artifactStore = FileSystemMigrationArtifactStore(
          projectDirectory: Directory(d.sandbox),
        );
      });

      group('when listing migration versions,', () {
        late List<String> versions;

        setUp(() async {
          versions = await artifactStore.listVersions();
        });

        test('then the empty trailing migration version is not listed.', () {
          expect(versions, ['10000000000000']);
        });

        test(
          'then the empty trailing migration version directory is deleted.',
          () async {
            await d.dir('migrations', [d.nothing('20000000000000')]).validate();
          },
        );

        test(
          'then the migration registry no longer lists the empty trailing '
          'migration version.',
          () async {
            await d.dir('migrations', [
              d.file(
                'migration_registry.txt',
                '${_migrationRegistryHeader}10000000000000\n',
              ),
            ]).validate();
          },
        );
      });
    },
  );

  group(
    'Given a file system migration artifact store without a migration '
    'registry and where the last migration version directory is empty,',
    () {
      late FileSystemMigrationArtifactStore artifactStore;

      setUp(() async {
        await d.dir('migrations', [
          d.dir('10000000000000', [d.file('definition.json', '{}')]),
          d.dir('20000000000000'),
        ]).create();

        artifactStore = FileSystemMigrationArtifactStore(
          projectDirectory: Directory(d.sandbox),
        );
      });

      group('when listing migration versions,', () {
        late List<String> versions;

        setUp(() async {
          versions = await artifactStore.listVersions();
        });

        test('then the empty trailing migration version is not listed.', () {
          expect(versions, ['10000000000000']);
        });

        test(
          'then the empty trailing migration version directory is deleted.',
          () async {
            await d.dir('migrations', [
              d.nothing('20000000000000'),
            ]).validate();
          },
        );

        test('then no migration registry is created.', () async {
          await d.dir('migrations', [
            d.nothing('migration_registry.txt'),
          ]).validate();
        });
      });
    },
  );

  group(
    'Given a file system migration artifact store where the two last '
    'migration version directories are empty,',
    () {
      late FileSystemMigrationArtifactStore artifactStore;

      setUp(() async {
        await d.dir('migrations', [
          d.dir('10000000000000', [d.file('definition.json', '{}')]),
          d.dir('20000000000000'),
          d.dir('30000000000000'),
        ]).create();

        artifactStore = FileSystemMigrationArtifactStore(
          projectDirectory: Directory(d.sandbox),
        );
      });

      group('when listing migration versions,', () {
        late List<String> versions;

        setUp(() async {
          versions = await artifactStore.listVersions();
        });

        test('then no empty trailing migration version is listed.', () {
          expect(versions, ['10000000000000']);
        });

        test(
          'then all empty trailing migration version directories are deleted.',
          () async {
            await d.dir('migrations', [
              d.nothing('20000000000000'),
              d.nothing('30000000000000'),
            ]).validate();
          },
        );
      });
    },
  );

  group(
    'Given a file system migration artifact store where the last migration '
    'version directory holds a file but no migration artifacts,',
    () {
      late FileSystemMigrationArtifactStore artifactStore;

      setUp(() async {
        await d.dir('migrations', [
          d.dir('10000000000000', [d.file('definition.json', '{}')]),
          d.dir('20000000000000', [d.file('unrelated.txt', '')]),
        ]).create();

        artifactStore = FileSystemMigrationArtifactStore(
          projectDirectory: Directory(d.sandbox),
        );
      });

      group('when listing migration versions,', () {
        late List<String> versions;

        setUp(() async {
          versions = await artifactStore.listVersions();
        });

        test('then all migration versions are listed.', () {
          expect(versions, ['10000000000000', '20000000000000']);
        });

        test(
          'then the trailing migration version directory is kept.',
          () async {
            await d.dir('migrations', [
              d.dir('20000000000000', [d.file('unrelated.txt', '')]),
            ]).validate();
          },
        );
      });
    },
  );

  group(
    'Given a file system migration artifact store without any empty migration '
    'version directory,',
    () {
      late FileSystemMigrationArtifactStore artifactStore;

      setUp(() async {
        await d.dir('migrations', [
          d.file(
            'migration_registry.txt',
            '${_migrationRegistryHeader}10000000000000\n20000000000000\n',
          ),
          d.dir('10000000000000', [d.file('definition.json', '{}')]),
          d.dir('20000000000000', [d.file('definition.json', '{}')]),
        ]).create();

        artifactStore = FileSystemMigrationArtifactStore(
          projectDirectory: Directory(d.sandbox),
        );
      });

      group('when listing migration versions,', () {
        late List<String> versions;

        setUp(() async {
          versions = await artifactStore.listVersions();
        });

        test('then all migration versions are listed.', () {
          expect(versions, ['10000000000000', '20000000000000']);
        });

        test('then the migration registry is left untouched.', () async {
          await d.dir('migrations', [
            d.file(
              'migration_registry.txt',
              '${_migrationRegistryHeader}10000000000000\n20000000000000\n',
            ),
          ]).validate();
        });
      });
    },
  );
}
