include: package:serverpod_lints/public.yaml

analyzer:
  exclude:
    - lib/src/generated/**

linter:
  rules:
    prefer_initializing_formals: false
    unnecessary_parenthesis: true

formatter:
  trailing_commas: preserve
