type: module
nickname: serverpod_auth_google_account

modules:
  serverpod_auth_user:
    nickname: auth_user

client_package_path: ../serverpod_auth_google_account_client
server_test_tools_path: test/integration/test_tools
