#!/bin/sh

# Reset tables
docker-compose run postgres env PGPASSWORD="password" psql -h postgres -p 5432 -U postgres -d serverpod_test < ../docker/reset_db.pgsql

# Create tables in database container
docker-compose run postgres env PGPASSWORD="password" psql -h postgres -p 5432 -U postgres -d serverpod_test < ../../packages/serverpod/generated/tables.pgsql
docker-compose run postgres env PGPASSWORD="password" psql -h postgres -p 5432 -U postgres -d serverpod_test < generated/tables.pgsql
