#!/bin/sh

if [ ! -f tests/docker/tests_single_server/docker-compose.yml ]; then
    echo "Run this script from the root of the Serverpod repository"
    echo "I.e. util/pub_get_all"
    exit 1
fi

if [[ $(git status -s) ]]
then
    echo "Files have been changed while running this test."
    git status -s
    exit 1
fi
