#!/bin/sh

if [ ! -f tests/docker/tests_single_server/docker-compose.yml ]; then
    echo "Run this script from the root of the Serverpod repository"
    echo "I.e. util/pub_get_all"
    exit 1
fi

BASE=`pwd`

echo "pub get cli"
cd $BASE/tools/serverpod_cli
dart pub get

echo "serverpod"
cd $BASE/packages/serverpod
serverpod generate

echo "serverpod/example/example_server"
cd $BASE/packages/serverpod/example/example_server
serverpod generate

# Templates

echo "\nmodulename_server"
cd $BASE/templates/serverpod_templates/modulename_server
serverpod generate

echo "\nprojectname_server"
cd $BASE/templates/serverpod_templates/projectname_server
serverpod generate

# Auth module

echo "\nserverpod_auth_server"
cd $BASE/modules/serverpod_auth/serverpod_auth_server
serverpod generate

# Chat module

echo "\nserverpod_chat_server"
cd $BASE/modules/serverpod_chat/serverpod_chat_server
serverpod generate
