#!/bin/bash

if [ ! -f util/.serverpod_util_root ]; then
    echo "Run this script from the root of the Serverpod repository"
    echo "I.e. util/pub_get_all"
    exit 1
fi

set -e

. "util/all_packages"

BASE=$(pwd)
OFFLINE_MODE=""
PUB_MODE="upgrade"
for arg in "$@"
do
  # Check for --offline parameter
  if [ "$arg" == "--offline" ]; then
      OFFLINE_MODE="--offline"
      echo "Running in offline mode"
  elif [ "$arg" == "--downgrade" ]; then
      PUB_MODE="downgrade"
      echo "Running in downgrade mode"
  fi
done

echo "PUB UPGRADE ALL"

# Upgrade Dart packages
for path in "${DART_PACKAGES_PATHS[@]}"; do
  echo "\n### $path"
  cd "$BASE/$path"
  dart pub $PUB_MODE $OFFLINE_MODE
done

# Upgrade Flutter packages
for path in "${FLUTTER_PACKAGES_PATHS[@]}"; do
  echo "\n### $path"
  cd "$BASE/$path"
  flutter pub $PUB_MODE $OFFLINE_MODE
done
