#!/bin/sh

BASE=`pwd`

echo "serverpod"
cd $BASE/packages/serverpod
dart pub get

echo "\nserverpod_client"
cd $BASE/packages/serverpod_client
dart pub get

echo "\nserverpod_relic"
cd $BASE/packages/serverpod_relic
dart pub get

echo "\nserverpod_serialization"
cd $BASE/packages/serverpod_serialization
dart pub get

echo "\nserverpod_service_client"
cd $BASE/packages/serverpod_service_client
dart pub get

echo "\nserverpod_shared"
cd $BASE/packages/serverpod_shared
dart pub get

echo "\nserverpod_test_client"
cd $BASE/tests/serverpod_test_client
dart pub get

echo "\nserverpod_test_server"
cd $BASE/tests/serverpod_test_server
dart pub get

echo "\nserverpod_test_module_client"
cd $BASE/tests/serverpod_test_module/serverpod_test_module_client
dart pub get

echo "\nserverpod_test_module_server"
cd $BASE/tests/serverpod_test_module/serverpod_test_module_server
dart pub get

echo "\nserverpod_cli"
cd $BASE/tools/serverpod_cli
dart pub get

# echo "\nserverpod_gui"
# cd ../serverpod_gui
# flutter packages get
