#!/bin/sh

BASE=`pwd`

echo "Base directory $BASE"

if test -z "$1"
then
  echo "Version number is not defined"
  exit
fi

if [[ $(git diff --stat) != '' ]]; then
  echo 'Git is dirty. Please commit all changes before publishing.'
  exit
else
  echo 'Git is clean'
fi

echo "Publish Serverpod version $1"

echo "Updating pubspecs"
cd $BASE
serverpod generate-pubspecs --version $1 --mode production
echo "dart pub get"
util/pub_get_all
#
# echo "Publish packages"
#
# # cd packages/serverpod_serialization
# # pub publish
#
# cd $BASE
# echo "Restore pubspecs"
# serverpod generate-pubspecs --version $1 --mode development
# echo "pub get"
# util/pub_get_all

echo "Restore pubspecs"
cd $BASE
git reset --hard HEAD

echo "dart pub get"
util/pub_get_all
