#!/bin/sh

BASE=`pwd`

echo "Base directory $BASE"

VERSION=`cat VERSION`
VERSION=$VERSION | xargs

if test -z "$VERSION"
then
  echo "Version number is not defined"
  exit
fi

if [[ $(git diff --stat) != '' ]]; then
  echo 'Git is dirty. Please commit all changes before publishing.'
  exit
else
  echo 'Git is clean'
fi

echo "Publish Serverpod version $VERSION"

echo "Updating pubspecs"
cd $BASE
serverpod generate-pubspecs --version $VERSION --mode production

echo "Publish packages"

cd $BASE/packages/serverpod_serialization
dart pub publish

cd $BASE/packages/serverpod_client
dart pub publish

cd $BASE/packages/serverpod_service_client
dart pub publish

cd $BASE/packages/serverpod_shared
dart pub publish

cd $BASE/tests/serverpod_test_module/serverpod_test_module_client
dart pub publish

cd $BASE/tests/serverpod_test_client
dart pub publish

cd $BASE/packages/serverpod
dart pub publish

cd $BASE/packages/serverpod_relic
dart pub publish

cd $BASE/tools/serverpod_cli
dart pub publish

echo "Restore pubspecs"
cd $BASE
git reset --hard HEAD

echo "dart pub get"
util/pub_get_all
