#!/bin/sh

if [ ! -f tests/docker/tests_single_server/docker-compose.yml ]; then
    echo "Run this script from the root of the Serverpod repository"
    echo "I.e. util/pub_get_all"
    exit 1
fi

BASE=`pwd`
CLI_DIR=$BASE/tools/serverpod_cli
CLI=$CLI_DIR/bin/serverpod_cli.dart
MIGRATION_DIR=generated/migration/migrations

echo "pub get cli"
cd $CLI_DIR
dart pub get

# Packages

echo "serverpod"
cd $BASE/packages/serverpod
rm -r $MIGRATION_DIR/serverpod
dart $CLI create-migration

# Examples

echo "examples/chat/chat_server"
cd $BASE/examples/chat/chat_server
rm -r $MIGRATION_DIR/chat
dart $CLI create-migration

# Modules 

echo "\nserverpod_auth_server"
cd $BASE/modules/serverpod_auth/serverpod_auth_server
rm -r $MIGRATION_DIR/serverpod_auth
dart $CLI create-migration

echo "\nserverpod_chat_server"
cd $BASE/modules/serverpod_chat/serverpod_chat_server
rm -r $MIGRATION_DIR/serverpod_chat
dart $CLI create-migration

# Tests

echo "\ntests/serverpod_test_server"
cd $BASE/tests/serverpod_test_server
rm -r $MIGRATION_DIR/serverpod_test
dart $CLI create-migration
