#!/bin/bash

# Runs a server package's integration tests against an embedded PG
#
# Usage:
#   util/run_tests_integration_embedded <server-directory>

if [ ! -f util/.serverpod_util_root ]; then
    echo "Run this script from the root of the Serverpod repository"
    echo "I.e. util/run_tests_integration_embedded <server-directory>"
    exit 1
fi

SERVER_DIR="$1"
if [ -z "$SERVER_DIR" ]; then
    echo "Usage: util/run_tests_integration_embedded <server-directory>"
    exit 1
fi
if [ ! -d "$SERVER_DIR" ]; then
    echo "No such server directory: $SERVER_DIR"
    exit 1
fi

set -e
export SERVERPOD_SILENCE_LIFECYCLE_MESSAGES="1"
export SERVERPOD_DATABASE_DATA_PATH=".serverpod/test/pgdata"

REPO_ROOT="$(pwd)"

cd "$SERVER_DIR"

dart test -t integration --reporter=failures-only

# Verify that the database data path exists
if [ ! -d "$SERVERPOD_DATABASE_DATA_PATH" ]; then
    echo "Test did not create the database data path: $SERVERPOD_DATABASE_DATA_PATH"
    cd "$REPO_ROOT"
    exit 1
fi

# Remove the database data path
rm -rf "$SERVERPOD_DATABASE_DATA_PATH"

cd "$REPO_ROOT"
