#!/bin/bash

# Runs the serverpod_auth_test_server integration tests against an embedded PG
#
if [ ! -f util/.serverpod_util_root ]; then
    echo "Run this script from the root of the Serverpod repository"
    echo "I.e. util/run_tests_auth_integration_embedded"
    exit 1
fi

set -e
export SERVERPOD_SILENCE_LIFECYCLE_MESSAGES="1"
export SERVERPOD_DATABASE_DATA_PATH=".serverpod/test/pgdata"

REPO_ROOT="$(pwd)"

cd "tests/serverpod_auth_test/serverpod_auth_test_server"

dart test -t integration --reporter=failures-only

# Verify that the database data path exists
if [ ! -d "$SERVERPOD_DATABASE_DATA_PATH" ]; then
    echo "Test did not create the database data path: $SERVERPOD_DATABASE_DATA_PATH"
    cd "$REPO_ROOT"
    exit 1
fi

# Remove the database data path
rm -rf "$SERVERPOD_DATABASE_DATA_PATH"

cd "$REPO_ROOT"
