#!/bin/sh

if [ ! -f tests/docker/tests_single_server/docker-compose.yml ]; then
    echo "Run this script from the root of the Serverpod repository"
    echo "I.e. util/run_tests"
    exit 1
fi

# Makes script exit on first non-zero error code
set -e

echo "### Checking dart format"
dart format -o none --set-exit-if-changed .
echo ""

util/pub_get_all

util/run_tests_analyze

echo "### Running unit tests"
util/run_tests_single_server

echo "### Run serverpod generate tests"
util/run_tests_serverpod_generate
