#!/bin/sh

if [ ! -f tests/docker/tests_integration/docker-compose.yml ]; then
    echo "Run this script from the root of the Serverpod repository"
    echo "I.e. util/run_tests_integration"
    exit 1
fi

# Makes script exit on first non-zero error code
set -e

cd tests/docker/tests_integration

docker compose up --abort-on-container-exit --exit-code-from tests --build --remove-orphans