#!/bin/sh

if [ ! -f tests/docker/tests_single_server/docker-compose.yml ]; then
    echo "Run this script from the root of the Serverpod repository"
    echo "I.e. util/update_pubspecs"
    exit 1
fi

VERSION=`cat VERSION`
VERSION=$VERSION | xargs

echo "Update all pubspecs. Version is $VERSION."

serverpod generate-pubspecs --version $VERSION --mode development

echo "Copying CHANGELOG.md"
cp CHANGELOG.md packages/serverpod/CHANGELOG.md
cp CHANGELOG.md packages/serverpod_client/CHANGELOG.md
cp CHANGELOG.md packages/serverpod_serialization/CHANGELOG.md
cp CHANGELOG.md packages/serverpod_service_client/CHANGELOG.md
cp CHANGELOG.md packages/serverpod_shared/CHANGELOG.md
cp CHANGELOG.md packages/serverpod_flutter/CHANGELOG.md

cp CHANGELOG.md templates/serverpod_templates/CHANGELOG.md
cp CHANGELOG.md tools/serverpod_cli/CHANGELOG.md
cp CHANGELOG.md tests/serverpod_test_client/CHANGELOG.md
cp CHANGELOG.md tests/serverpod_test_server/CHANGELOG.md
cp CHANGELOG.md tests/serverpod_test_module/serverpod_test_module_client/CHANGELOG.md
cp CHANGELOG.md tests/serverpod_test_module/serverpod_test_module_server/CHANGELOG.md

cp CHANGELOG.md modules/serverpod_auth/serverpod_auth_server/CHANGELOG.md
cp CHANGELOG.md modules/serverpod_auth/serverpod_auth_client/CHANGELOG.md
cp CHANGELOG.md modules/serverpod_auth/serverpod_auth_shared_flutter/CHANGELOG.md
cp CHANGELOG.md modules/serverpod_auth/serverpod_auth_email_flutter/CHANGELOG.md
cp CHANGELOG.md modules/serverpod_auth/serverpod_auth_apple_flutter/CHANGELOG.md
cp CHANGELOG.md modules/serverpod_auth/serverpod_auth_google_flutter/CHANGELOG.md
cp CHANGELOG.md modules/serverpod_auth/serverpod_auth_firebase_flutter/CHANGELOG.md

cp CHANGELOG.md modules/serverpod_chat/serverpod_chat_server/CHANGELOG.md
cp CHANGELOG.md modules/serverpod_chat/serverpod_chat_client/CHANGELOG.md
cp CHANGELOG.md modules/serverpod_chat/serverpod_chat_flutter/CHANGELOG.md

cp CHANGELOG.md integrations/serverpod_cloud_storage_s3/CHANGELOG.md
cp CHANGELOG.md integrations/serverpod_cloud_storage_gcp/CHANGELOG.md

echo "Copying README.md"
cp README.md packages/serverpod/README.md
cp README_subpackage.md packages/serverpod_client/README.md
cp README_subpackage.md packages/serverpod_serialization/README.md
cp README_subpackage.md packages/serverpod_service_client/README.md
cp README_subpackage.md packages/serverpod_shared/README.md
cp README_subpackage.md packages/serverpod_flutter/README.md

cp README_subpackage.md templates/serverpod_templates/README.md
cp README_subpackage.md tools/serverpod_cli/README.md
cp README_subpackage.md tests/serverpod_test_client/README.md
cp README_subpackage.md tests/serverpod_test_server/README.md
cp README_subpackage.md tests/serverpod_test_module/serverpod_test_module_client/README.md
cp README_subpackage.md tests/serverpod_test_module/serverpod_test_module_server/README.md

cp README_subpackage.md modules/serverpod_auth/serverpod_auth_server/README.md
cp README_subpackage.md modules/serverpod_auth/serverpod_auth_client/README.md
cp README_subpackage.md modules/serverpod_auth/serverpod_auth_shared_flutter/README.md
cp README_subpackage.md modules/serverpod_auth/serverpod_auth_email_flutter/README.md
cp README_subpackage.md modules/serverpod_auth/serverpod_auth_apple_flutter/README.md
cp README_subpackage.md modules/serverpod_auth/serverpod_auth_google_flutter/README.md
cp README_subpackage.md modules/serverpod_auth/serverpod_auth_firebase_flutter/README.md

cp README_subpackage.md modules/serverpod_chat/serverpod_chat_server/README.md
cp README_subpackage.md modules/serverpod_chat/serverpod_chat_client/README.md
cp README_subpackage.md modules/serverpod_chat/serverpod_chat_flutter/README.md

cp README_subpackage.md integrations/serverpod_cloud_storage_s3/README.md
cp README_subpackage.md integrations/serverpod_cloud_storage_gcp/README.md

echo "Copy tables"
cp packages/serverpod/generated/tables.pgsql templates/serverpod_templates/projectname_server/generated/tables-serverpod.pgsql
cp packages/serverpod/generated/tables.pgsql examples/chat/chat_server/generated/tables-serverpod.pgsql
cp packages/serverpod/generated/tables.pgsql examples/auth_example/auth_example_server/generated/tables-serverpod.pgsql
