name: serverpod_auth_passkey_server
description: Serverpod authentication passkey server module.
version: 2.9.1
repository: https://github.com/serverpod/serverpod

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  clock: ^1.1.1
  crypto: ^3.0.2
  meta: ^1.11.0
  serverpod: 2.9.1
  serverpod_auth_passkey_account_server: 2.9.1
  serverpod_auth_user_server: 2.9.1
  serverpod_shared: 2.9.1

dev_dependencies:
  serverpod_lints: 2.9.1
  serverpod_test: 2.9.1
  test: "^1.24.2"

dependency_overrides:
  serverpod:
    path: ../../../../packages/serverpod
  serverpod_auth_passkey_account_server:
    path: ../../serverpod_auth_passkey_account/serverpod_auth_passkey_account_server
  serverpod_auth_user_server:
    path: ../../../new_serverpod_auth/serverpod_auth_user/serverpod_auth_user_server
  serverpod_lints:
    path: ../../../../packages/serverpod_lints
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
  serverpod_shared:
    path: ../../../../packages/serverpod_shared
  serverpod_test:
    path: ../../../../packages/serverpod_test
