name: modulename
publish_to: none

environment:
  sdk: '^3.12.2'

#workspace: #--UNCOMMENT_LINE--#
#  - modulename_client #--UNCOMMENT_LINE--#
#  - modulename_server #--UNCOMMENT_LINE--#

dependency_overrides:
  serverpod:
    path: ../../../packages/serverpod
  serverpod_client:
    path: ../../../packages/serverpod_client
  serverpod_database:
    path: ../../../packages/serverpod_database
  serverpod_embedded_postgres:
    path: ../../../packages/serverpod_embedded_postgres
  serverpod_lints:
    path: ../../../packages/serverpod_lints
  serverpod_serialization:
    path: ../../../packages/serverpod_serialization
  serverpod_shared:
    path: ../../../packages/serverpod_shared
  serverpod_test:
    path: ../../../packages/serverpod_test
