name: projectname_client
description: Starting point for a Serverpod client.

environment:
  sdk: '^3.10.3'

#resolution: workspace #--UNCOMMENT_LINE--#

dependencies:
  serverpod_client: 3.5.0-beta.7
