import 'dart:io';

import 'package:path/path.dart' as path;
import 'package:serverpod_serialization/serverpod_serialization.dart';
import 'package:serverpod_shared/serverpod_shared.dart';

import '../../../serverpod_database.dart';
import '../../definition/definition_normalizer.dart';

/// Stores migration artifacts using the current file-system based format.
class FileSystemMigrationArtifactStore
    implements MigrationArtifactStoreReader, MigrationArtifactStoreWriter {
  /// Creates a new file system migration artifact store.
  FileSystemMigrationArtifactStore({
    required Directory projectDirectory,
  }) : _projectDirectory = projectDirectory;

  final Directory _projectDirectory;

  static const _migrationRegistryHeader = '''
### AUTOMATICALLY GENERATED DO NOT MODIFY
###
### This file is generated by Serverpod when creating a migration, do not modify it
### manually. If a collision is detected in this file when doing a code merge, resolve
### the conflict by removing and recreating the conflicting migration.

''';

  @override
  Future<List<String>> listVersions() async {
    var migrationsDirectory = MigrationConstants.migrationsBaseDirectory(
      _projectDirectory,
    );

    if (!await migrationsDirectory.exists()) {
      return [];
    }

    var versions =
        await migrationsDirectory
              .list()
              .where((entity) => entity is Directory)
              .cast<Directory>()
              .map((directory) => path.basename(directory.path))
              .toList()
          ..sort();

    final prunedAny =
        await _deleteTrailingCompletelyEmptyMigrationVersionDirectories(
          versions,
        );

    if (prunedAny && await _migrationRegistryFile().exists()) {
      await writeVersionRegistry(versions);
    }

    return versions;
  }

  @override
  Future<MigrationVersionSql?> readVersionSql(String version) async {
    final versionDirectory = await _resolveVersionDirectory(version);
    if (versionDirectory == null) {
      return null;
    }

    final definition = await _readRequiredProtocolFile<DatabaseDefinition>(
      MigrationConstants.databaseDefinitionJSONPath(_projectDirectory, version),
    );

    return MigrationVersionSql(
      version: version,
      moduleName: definition.moduleName,
      definitionSql: await _readRequiredFile(
        MigrationConstants.databaseDefinitionSQLPath(
          _projectDirectory,
          version,
        ),
      ),
      migrationSql: await _readRequiredFile(
        MigrationConstants.databaseMigrationSQLPath(
          _projectDirectory,
          version,
        ),
      ),
    );
  }

  @override
  Future<MigrationVersionDefinition?> readVersionDefinition(
    String version,
  ) async {
    final versionDirectory = await _resolveVersionDirectory(version);
    if (versionDirectory == null) {
      return null;
    }

    var definition = await _readRequiredProtocolFile<DatabaseDefinition>(
      MigrationConstants.databaseDefinitionJSONPath(_projectDirectory, version),
    );

    var migration = await _readRequiredProtocolFile<DatabaseMigration>(
      MigrationConstants.databaseMigrationJSONPath(
        _projectDirectory,
        version,
      ),
    );

    return MigrationVersionDefinition(
      version: version,
      definition: normalizeDefinitionToV2(definition),
      projectDefinition: normalizeDefinitionToV2(
        await _readRequiredProtocolFile<DatabaseDefinition>(
          MigrationConstants.databaseDefinitionProjectJSONPath(
            _projectDirectory,
            version,
          ),
        ),
      ),
      migration: definition.schemaVersion < 2
          ? normalizeMigrationToV2(migration, definition)
          : migration,
    );
  }

  @override
  Future<String?> loadDefinitionModuleName(String version) async {
    final definition = await readVersionDefinition(version);
    return definition?.moduleName;
  }

  Future<Directory?> _resolveVersionDirectory(String version) async {
    var versionDirectory = MigrationConstants.migrationVersionDirectory(
      _projectDirectory,
      version,
    );
    if (!await versionDirectory.exists()) {
      return null;
    }
    return versionDirectory;
  }

  @override
  Future<void> writeVersion(MigrationVersionArtifacts artifacts) async {
    var versionDirectory = MigrationConstants.migrationVersionDirectory(
      _projectDirectory,
      artifacts.version,
    );
    if (await versionDirectory.exists()) {
      throw MigrationVersionAlreadyExistsException(
        directoryPath: versionDirectory.path,
      );
    }
    await versionDirectory.create(recursive: true);

    await _writeFile(
      MigrationConstants.databaseDefinitionProjectJSONPath(
        _projectDirectory,
        artifacts.version,
      ),
      _encodeProtocolObject(artifacts.projectDefinition),
    );
    await _writeFile(
      MigrationConstants.databaseDefinitionJSONPath(
        _projectDirectory,
        artifacts.version,
      ),
      _encodeProtocolObject(artifacts.definition),
    );
    await _writeFile(
      MigrationConstants.databaseDefinitionSQLPath(
        _projectDirectory,
        artifacts.version,
      ),
      artifacts.definitionSql,
    );
    await _writeFile(
      MigrationConstants.databaseMigrationJSONPath(
        _projectDirectory,
        artifacts.version,
      ),
      _encodeProtocolObject(artifacts.migration),
    );
    await _writeFile(
      MigrationConstants.databaseMigrationSQLPath(
        _projectDirectory,
        artifacts.version,
      ),
      artifacts.migrationSql,
    );
  }

  File _migrationRegistryFile() => File(
    path.join(
      MigrationConstants.migrationsBaseDirectory(_projectDirectory).path,
      'migration_registry.txt',
    ),
  );

  @override
  Future<void> writeVersionRegistry(List<String> versions) async {
    var registryFile = _migrationRegistryFile();

    var contents = StringBuffer(_migrationRegistryHeader);
    for (var version in versions) {
      contents.writeln(version);
    }

    await registryFile.parent.create(recursive: true);
    await registryFile.writeAsString(contents.toString());
  }

  @override
  Future<RepairMigration?> readRepairMigration() async {
    var repairMigrationDirectory = MigrationConstants.repairMigrationDirectory(
      _projectDirectory,
    );
    if (!await repairMigrationDirectory.exists()) {
      return null;
    }

    var repairMigrationFiles = await repairMigrationDirectory
        .list()
        .where((entity) => entity is File)
        .cast<File>()
        .where((file) => path.basename(file.path).endsWith('.sql'))
        .toList();

    if (repairMigrationFiles.isEmpty) {
      return null;
    }

    var migrationSqlFile = repairMigrationFiles.single;
    return RepairMigration(
      version: path.basename(migrationSqlFile.path).split('.').first,
      migrationSql: await migrationSqlFile.readAsString(),
    );
  }

  @override
  Future<void> writeRepairMigration(RepairMigration repairMigration) async {
    try {
      var repairMigrationDirectory =
          MigrationConstants.repairMigrationDirectory(
            _projectDirectory,
          );
      if (await repairMigrationDirectory.exists()) {
        await repairMigrationDirectory.delete(recursive: true);
      }
      await repairMigrationDirectory.create(recursive: true);

      var repairMigrationFile = File(
        path.join(
          repairMigrationDirectory.path,
          '${repairMigration.version}.sql',
        ),
      );
      await repairMigrationFile.writeAsString(repairMigration.migrationSql);
    } catch (e) {
      throw MigrationRepairWriteException(exception: e.toString());
    }
  }

  /// Removes migration version directories from the end of [versions] that
  /// contain no files or subdirectories (e.g. left over after discarding a
  /// migration). Directories that contain any entity but are missing required
  /// migration artifacts are left intact so callers can still report corruption.
  ///
  /// Returns `true` if at least one directory was deleted.
  Future<bool> _deleteTrailingCompletelyEmptyMigrationVersionDirectories(
    List<String> versions,
  ) async {
    var prunedAny = false;
    while (versions.isNotEmpty) {
      final version = versions.last;
      final versionDir = MigrationConstants.migrationVersionDirectory(
        _projectDirectory,
        version,
      );
      if (!await versionDir.exists()) {
        versions.removeLast();
        prunedAny = true;
        continue;
      }
      if (!await _directoryHasNoEntities(versionDir)) {
        break;
      }
      await versionDir.delete(recursive: false);
      versions.removeLast();
      prunedAny = true;
    }
    return prunedAny;
  }

  static Future<bool> _directoryHasNoEntities(Directory dir) async {
    await for (final _ in dir.list(followLinks: false)) {
      return false;
    }
    return true;
  }

  static Future<String?> _readFileIfExists(File file) async {
    try {
      return await file.readAsString();
    } on PathNotFoundException catch (_) {} // ignore
    return null;
  }

  static Future<String> _readRequiredFile(File file) async {
    var contents = await _readFileIfExists(file);
    if (contents == null) {
      throw Exception('Required migration artifact is missing: ${file.path}');
    }
    return contents;
  }

  static Future<T> _readRequiredProtocolFile<T>(File file) async {
    var contents = await _readRequiredFile(file);
    return Protocol().decode<T>(contents);
  }

  static Future<void> _writeFile(File file, String contents) async {
    await file.writeAsString(contents);
  }

  static String _encodeProtocolObject<T>(T value) {
    return SerializationManager.encode(value, formatted: true);
  }
}
