name: serverpod_auth_apple_account_client
description: Serverpod Sign in with Apple authentication core client module.

environment:
  sdk: DART_VERSION

dependencies:
  serverpod_auth_user_client: SERVERPOD_VERSION
  serverpod_client: SERVERPOD_VERSION

dependency_overrides:
  serverpod_auth_user_client:
    path: ../../serverpod_auth_user/serverpod_auth_user_client
  serverpod_client:
    path: ../../../../packages/serverpod_client
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
