type: module
nickname: serverpod_auth_jwt

modules:
  serverpod_auth_core:
    nickname: auth_core

client_package_path: ../serverpod_auth_jwt_client
server_test_tools_path: test/integration/test_tools
