name: serverpod_auth_migration_client
description: Serverpod authentication migration client module.
version: 2.9.1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  serverpod_auth_user_client: 2.9.1
  serverpod_client: 2.9.1

dependency_overrides:
  serverpod_auth_client:
    path: ../../../serverpod_auth/serverpod_auth_client
  serverpod_auth_user_client:
    path: ../../serverpod_auth_user/serverpod_auth_user_client
  serverpod_auth_email_account_client:
    path: ../../serverpod_auth_email_account/serverpod_auth_email_account_client
  serverpod_client:
    path: ../../../../packages/serverpod_client
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
