name: serverpod_auth_migration_client
description: Serverpod authentication migration client module.
version: 3.0.0-alpha.1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  serverpod_auth_core_client: 3.0.0-alpha.1
  serverpod_client: 3.0.0-alpha.1

dependency_overrides:
  serverpod_auth_core_client:
    path: ../../serverpod_auth_core/serverpod_auth_core_client
  serverpod_client:
    path: ../../../../packages/serverpod_client
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
