name: serverpod_auth_session_client
description: Serverpod authentication user session client module.
version: 2.6.0
repository: https://github.com/serverpod/serverpod

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  serverpod_client: 2.6.0
