name: serverpod_auth_apple_client
description: Serverpod Sign in with Apple authentication endpoint client module.
version: SERVERPOD_VERSION

environment:
  sdk: DART_VERSION

dependencies:
  serverpod_auth_apple_account_client: SERVERPOD_VERSION
  serverpod_auth_profile_client: SERVERPOD_VERSION
  serverpod_auth_session_client: SERVERPOD_VERSION
  serverpod_auth_user_client: SERVERPOD_VERSION
  serverpod_client: SERVERPOD_VERSION

dependency_overrides:
  serverpod_auth_apple_account_client:
    path: ../../serverpod_auth_apple_account/serverpod_auth_apple_account_client
  serverpod_auth_profile_client:
    path: ../../serverpod_auth_profile/serverpod_auth_profile_client
  serverpod_auth_session_client:
    path: ../../serverpod_auth_session/serverpod_auth_session_client
  serverpod_auth_user_client:
    path: ../../serverpod_auth_user/serverpod_auth_user_client
  serverpod_client:
    path: ../../../../packages/serverpod_client
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
