/// AUTOGENERATED BY SERVERPOD create-migration - DO NOT EDIT BY HAND
/// Merging: resolve registry conflicts the same as migration_registry.txt.
part of '../migration_registry.dart';

class _Migration20260425031610501 implements MigrationVersionSql {
  @override
  String get version => '20260425031610501';

  @override
  String get moduleName => 'serverpod_test_sqlite';

  @override
  String get migrationSql => '''BEGIN;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "address" (
    "id" INTEGER PRIMARY KEY,
    "street" TEXT NOT NULL,
    "inhabitantId" INTEGER,
    CONSTRAINT "address_fk_0" FOREIGN KEY ("inhabitantId") REFERENCES "citizen" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "inhabitant_index_idx" ON "address" ("inhabitantId");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "arena" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "blocking" (
    "id" INTEGER PRIMARY KEY,
    "blockedId" INTEGER NOT NULL,
    "blockedById" INTEGER NOT NULL,
    CONSTRAINT "blocking_fk_0" FOREIGN KEY ("blockedId") REFERENCES "member" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "blocking_fk_1" FOREIGN KEY ("blockedById") REFERENCES "member" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "blocking_blocked_unique_idx" ON "blocking" ("blockedId", "blockedById");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "book" (
    "id" INTEGER PRIMARY KEY,
    "title" TEXT NOT NULL
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "cat" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "motherId" INTEGER,
    CONSTRAINT "cat_fk_0" FOREIGN KEY ("motherId") REFERENCES "cat" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "chapter" (
    "id" INTEGER PRIMARY KEY,
    "title" TEXT NOT NULL,
    "_bookChaptersBookId" INTEGER,
    CONSTRAINT "chapter_fk_0" FOREIGN KEY ("_bookChaptersBookId") REFERENCES "book" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "citizen" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "companyId" INTEGER NOT NULL,
    "oldCompanyId" INTEGER,
    CONSTRAINT "citizen_fk_0" FOREIGN KEY ("companyId") REFERENCES "company" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "citizen_fk_1" FOREIGN KEY ("oldCompanyId") REFERENCES "company" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "city" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "comment" (
    "id" INTEGER PRIMARY KEY,
    "description" TEXT NOT NULL,
    "orderId" INTEGER NOT NULL,
    CONSTRAINT "comment_fk_0" FOREIGN KEY ("orderId") REFERENCES "order" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "company" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "townId" INTEGER NOT NULL,
    CONSTRAINT "company_fk_0" FOREIGN KEY ("townId") REFERENCES "town" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "course" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "customer" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "empty_model_relation_item" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "_relationEmptyModelItemsRelationEmptyModelId" INTEGER,
    CONSTRAINT "empty_model_relation_item_fk_0" FOREIGN KEY ("_relationEmptyModelItemsRelationEmptyModelId") REFERENCES "relation_empty_model" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "empty_model_with_table" (
    "id" INTEGER PRIMARY KEY
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "enrollment" (
    "id" INTEGER PRIMARY KEY,
    "studentId" INTEGER NOT NULL,
    "courseId" INTEGER NOT NULL,
    CONSTRAINT "enrollment_fk_0" FOREIGN KEY ("studentId") REFERENCES "student" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "enrollment_fk_1" FOREIGN KEY ("courseId") REFERENCES "course" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "enrollment_index_idx" ON "enrollment" ("studentId", "courseId");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "member" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "model_with_required_field" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "email" TEXT,
    "phone" TEXT
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "object_field_persist" (
    "id" INTEGER PRIMARY KEY,
    "normal" TEXT NOT NULL
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "order" (
    "id" INTEGER PRIMARY KEY,
    "description" TEXT NOT NULL,
    "customerId" INTEGER NOT NULL,
    CONSTRAINT "order_fk_0" FOREIGN KEY ("customerId") REFERENCES "customer" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "organization" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "cityId" INTEGER,
    CONSTRAINT "organization_fk_0" FOREIGN KEY ("cityId") REFERENCES "city" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "person" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "organizationId" INTEGER,
    "_cityCitizensCityId" INTEGER,
    CONSTRAINT "person_fk_0" FOREIGN KEY ("organizationId") REFERENCES "organization" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "person_fk_1" FOREIGN KEY ("_cityCitizensCityId") REFERENCES "city" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "player" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "teamId" INTEGER,
    CONSTRAINT "player_fk_0" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "post" (
    "id" INTEGER PRIMARY KEY,
    "content" TEXT NOT NULL,
    "nextId" INTEGER,
    CONSTRAINT "post_fk_0" FOREIGN KEY ("nextId") REFERENCES "post" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "next_unique_idx" ON "post" ("nextId");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "related_unique_data" (
    "id" INTEGER PRIMARY KEY,
    "uniqueDataId" INTEGER NOT NULL,
    "number" INTEGER NOT NULL,
    CONSTRAINT "related_unique_data_fk_0" FOREIGN KEY ("uniqueDataId") REFERENCES "unique_data" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "relation_empty_model" (
    "id" INTEGER PRIMARY KEY
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "simple_data" (
    "id" INTEGER PRIMARY KEY,
    "num" INTEGER NOT NULL
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "simple_date_time" (
    "id" INTEGER PRIMARY KEY,
    "dateTime" INTEGER NOT NULL
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "student" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "team" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "arenaId" INTEGER,
    CONSTRAINT "team_fk_0" FOREIGN KEY ("arenaId") REFERENCES "arena" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "arena_index_idx" ON "team" ("arenaId");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "town" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "mayorId" INTEGER,
    CONSTRAINT "town_fk_0" FOREIGN KEY ("mayorId") REFERENCES "citizen" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "types" (
    "id" INTEGER PRIMARY KEY,
    "anInt" INTEGER,
    "aBool" INTEGER,
    "aDouble" REAL,
    "aDateTime" INTEGER,
    "aString" TEXT,
    "aByteData" BLOB,
    "aDuration" INTEGER,
    "aUuid" BLOB,
    "aUri" TEXT,
    "aBigInt" TEXT,
    "aVector" TEXT,
    "aHalfVector" TEXT,
    "aSparseVector" TEXT,
    "aBit" TEXT,
    "anEnum" INTEGER,
    "aStringifiedEnum" TEXT,
    "aList" TEXT,
    "aMap" TEXT,
    "aSet" TEXT,
    "aRecord" TEXT
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "unique_data" (
    "id" INTEGER PRIMARY KEY,
    "number" INTEGER NOT NULL,
    "email" TEXT NOT NULL
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "email_index_idx" ON "unique_data" ("email");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "unique_data_with_non_persist" (
    "id" INTEGER PRIMARY KEY,
    "number" INTEGER NOT NULL,
    "email" TEXT NOT NULL
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "unique_email_idx" ON "unique_data_with_non_persist" ("email");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "serverpod_cloud_storage" (
    "id" INTEGER PRIMARY KEY,
    "storageId" TEXT NOT NULL,
    "path" TEXT NOT NULL,
    "addedTime" INTEGER NOT NULL,
    "expiration" INTEGER,
    "byteData" BLOB NOT NULL,
    "verified" INTEGER NOT NULL
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "serverpod_cloud_storage_path_idx" ON "serverpod_cloud_storage" ("storageId", "path");
CREATE INDEX "serverpod_cloud_storage_expiration" ON "serverpod_cloud_storage" ("expiration");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "serverpod_cloud_storage_direct_upload" (
    "id" INTEGER PRIMARY KEY,
    "storageId" TEXT NOT NULL,
    "path" TEXT NOT NULL,
    "expiration" INTEGER NOT NULL,
    "authKey" TEXT NOT NULL
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "serverpod_cloud_storage_direct_upload_storage_path" ON "serverpod_cloud_storage_direct_upload" ("storageId", "path");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "serverpod_future_call" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "time" INTEGER NOT NULL,
    "serializedObject" TEXT,
    "serverId" TEXT NOT NULL,
    "identifier" TEXT,
    "scheduling" TEXT
) STRICT;

-- Indexes
CREATE INDEX "serverpod_future_call_time_idx" ON "serverpod_future_call" ("time");
CREATE INDEX "serverpod_future_call_serverId_idx" ON "serverpod_future_call" ("serverId");
CREATE INDEX "serverpod_future_call_identifier_idx" ON "serverpod_future_call" ("identifier");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "serverpod_future_call_claim" (
    "id" INTEGER PRIMARY KEY,
    "futureCallId" INTEGER,
    "lastHeartbeatTime" INTEGER NOT NULL,
    CONSTRAINT "serverpod_future_call_claim_fk_0" FOREIGN KEY ("futureCallId") REFERENCES "serverpod_future_call" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "future_call_unique_idx" ON "serverpod_future_call_claim" ("futureCallId");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "serverpod_health_connection_info" (
    "id" INTEGER PRIMARY KEY,
    "serverId" TEXT NOT NULL,
    "timestamp" INTEGER NOT NULL,
    "active" INTEGER NOT NULL,
    "closing" INTEGER NOT NULL,
    "idle" INTEGER NOT NULL,
    "granularity" INTEGER NOT NULL
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "serverpod_health_connection_info_timestamp_idx" ON "serverpod_health_connection_info" ("timestamp", "serverId", "granularity");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "serverpod_health_metric" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "serverId" TEXT NOT NULL,
    "timestamp" INTEGER NOT NULL,
    "isHealthy" INTEGER NOT NULL,
    "value" REAL NOT NULL,
    "granularity" INTEGER NOT NULL
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "serverpod_health_metric_timestamp_idx" ON "serverpod_health_metric" ("timestamp", "serverId", "name", "granularity");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "serverpod_log" (
    "id" INTEGER PRIMARY KEY,
    "sessionLogId" INTEGER NOT NULL,
    "messageId" INTEGER,
    "reference" TEXT,
    "serverId" TEXT NOT NULL,
    "time" INTEGER NOT NULL,
    "logLevel" INTEGER NOT NULL,
    "message" TEXT NOT NULL,
    "error" TEXT,
    "stackTrace" TEXT,
    "order" INTEGER NOT NULL,
    CONSTRAINT "serverpod_log_fk_0" FOREIGN KEY ("sessionLogId") REFERENCES "serverpod_session_log" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
) STRICT;

-- Indexes
CREATE INDEX "serverpod_log_sessionLogId_idx" ON "serverpod_log" ("sessionLogId", "order");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "serverpod_message_log" (
    "id" INTEGER PRIMARY KEY,
    "sessionLogId" INTEGER NOT NULL,
    "serverId" TEXT NOT NULL,
    "messageId" INTEGER NOT NULL,
    "endpoint" TEXT NOT NULL,
    "messageName" TEXT NOT NULL,
    "duration" REAL NOT NULL,
    "error" TEXT,
    "stackTrace" TEXT,
    "slow" INTEGER NOT NULL,
    "order" INTEGER NOT NULL,
    CONSTRAINT "serverpod_message_log_fk_0" FOREIGN KEY ("sessionLogId") REFERENCES "serverpod_session_log" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
) STRICT;

-- Indexes
CREATE INDEX "serverpod_message_log_sessionLogId_idx" ON "serverpod_message_log" ("sessionLogId", "order");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "serverpod_method" (
    "id" INTEGER PRIMARY KEY,
    "endpoint" TEXT NOT NULL,
    "method" TEXT NOT NULL
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "serverpod_method_endpoint_method_idx" ON "serverpod_method" ("endpoint", "method");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "serverpod_migrations" (
    "id" INTEGER PRIMARY KEY,
    "module" TEXT NOT NULL,
    "version" TEXT NOT NULL,
    "timestamp" INTEGER
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "serverpod_migrations_ids" ON "serverpod_migrations" ("module");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "serverpod_query_log" (
    "id" INTEGER PRIMARY KEY,
    "serverId" TEXT NOT NULL,
    "sessionLogId" INTEGER NOT NULL,
    "messageId" INTEGER,
    "query" TEXT NOT NULL,
    "duration" REAL NOT NULL,
    "numRows" INTEGER,
    "error" TEXT,
    "stackTrace" TEXT,
    "slow" INTEGER NOT NULL,
    "order" INTEGER NOT NULL,
    CONSTRAINT "serverpod_query_log_fk_0" FOREIGN KEY ("sessionLogId") REFERENCES "serverpod_session_log" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
) STRICT;

-- Indexes
CREATE INDEX "serverpod_query_log_sessionLogId_idx" ON "serverpod_query_log" ("sessionLogId", "order");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "serverpod_readwrite_test" (
    "id" INTEGER PRIMARY KEY,
    "number" INTEGER NOT NULL
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "serverpod_runtime_settings" (
    "id" INTEGER PRIMARY KEY,
    "logSettings" TEXT NOT NULL,
    "logSettingsOverrides" TEXT NOT NULL,
    "logServiceCalls" INTEGER NOT NULL,
    "logMalformedCalls" INTEGER NOT NULL
) STRICT;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "serverpod_session_log" (
    "id" INTEGER PRIMARY KEY,
    "serverId" TEXT NOT NULL,
    "time" INTEGER NOT NULL,
    "module" TEXT,
    "endpoint" TEXT,
    "method" TEXT,
    "duration" REAL,
    "numQueries" INTEGER,
    "slow" INTEGER,
    "error" TEXT,
    "stackTrace" TEXT,
    "authenticatedUserId" INTEGER,
    "userId" TEXT,
    "isOpen" INTEGER,
    "touched" INTEGER NOT NULL
) STRICT;

-- Indexes
CREATE INDEX "serverpod_session_log_serverid_idx" ON "serverpod_session_log" ("serverId");
CREATE INDEX "serverpod_session_log_time_idx" ON "serverpod_session_log" ("time");
CREATE INDEX "serverpod_session_log_touched_idx" ON "serverpod_session_log" ("touched");
CREATE INDEX "serverpod_session_log_isopen_idx" ON "serverpod_session_log" ("isOpen");

--
-- STORE COLUMN TYPES FOR MIGRATIONS
--
DROP TABLE IF EXISTS "serverpod_sqlite_schema";

CREATE TABLE "serverpod_sqlite_schema" (
    "table_name" TEXT NOT NULL,
    "column_name" TEXT NOT NULL,
    "column_type" TEXT NOT NULL,
    "column_vector_dimension" INTEGER,
    PRIMARY KEY ("table_name", "column_name")
);

INSERT INTO "serverpod_sqlite_schema" VALUES
    ('simple_date_time', 'dateTime', 'timestampWithoutTimeZone', NULL),
    ('types', 'aBool', 'boolean', NULL),
    ('types', 'aDateTime', 'timestampWithoutTimeZone', NULL),
    ('types', 'aUuid', 'uuid', NULL),
    ('types', 'aVector', 'vector', 3),
    ('types', 'aHalfVector', 'halfvec', 3),
    ('types', 'aSparseVector', 'sparsevec', 3),
    ('types', 'aBit', 'bit', 3),
    ('types', 'aList', 'json', NULL),
    ('types', 'aMap', 'json', NULL),
    ('types', 'aSet', 'json', NULL),
    ('types', 'aRecord', 'json', NULL),
    ('serverpod_cloud_storage', 'addedTime', 'timestampWithoutTimeZone', NULL),
    ('serverpod_cloud_storage', 'expiration', 'timestampWithoutTimeZone', NULL),
    ('serverpod_cloud_storage', 'verified', 'boolean', NULL),
    ('serverpod_cloud_storage_direct_upload', 'expiration', 'timestampWithoutTimeZone', NULL),
    ('serverpod_future_call', 'time', 'timestampWithoutTimeZone', NULL),
    ('serverpod_future_call', 'scheduling', 'json', NULL),
    ('serverpod_future_call_claim', 'lastHeartbeatTime', 'timestampWithoutTimeZone', NULL),
    ('serverpod_health_connection_info', 'timestamp', 'timestampWithoutTimeZone', NULL),
    ('serverpod_health_metric', 'timestamp', 'timestampWithoutTimeZone', NULL),
    ('serverpod_health_metric', 'isHealthy', 'boolean', NULL),
    ('serverpod_log', 'time', 'timestampWithoutTimeZone', NULL),
    ('serverpod_message_log', 'slow', 'boolean', NULL),
    ('serverpod_migrations', 'timestamp', 'timestampWithoutTimeZone', NULL),
    ('serverpod_query_log', 'slow', 'boolean', NULL),
    ('serverpod_runtime_settings', 'logSettings', 'json', NULL),
    ('serverpod_runtime_settings', 'logSettingsOverrides', 'json', NULL),
    ('serverpod_runtime_settings', 'logServiceCalls', 'boolean', NULL),
    ('serverpod_runtime_settings', 'logMalformedCalls', 'boolean', NULL),
    ('serverpod_session_log', 'time', 'timestampWithoutTimeZone', NULL),
    ('serverpod_session_log', 'slow', 'boolean', NULL),
    ('serverpod_session_log', 'isOpen', 'boolean', NULL),
    ('serverpod_session_log', 'touched', 'timestampWithoutTimeZone', NULL);

--
-- MIGRATION VERSION FOR serverpod_test_sqlite
--
INSERT INTO "serverpod_migrations" ("module", "version", "timestamp")
    VALUES ('serverpod_test_sqlite', '20260425031610501', (unixepoch('now', 'subsecond') * 1000))
    ON CONFLICT ("module")
    DO UPDATE SET "version" = '20260425031610501', "timestamp" = (unixepoch('now', 'subsecond') * 1000);

--
-- MIGRATION VERSION FOR serverpod
--
INSERT INTO "serverpod_migrations" ("module", "version", "timestamp")
    VALUES ('serverpod', '20260416151914983-insights-perf', (unixepoch('now', 'subsecond') * 1000))
    ON CONFLICT ("module")
    DO UPDATE SET "version" = '20260416151914983-insights-perf', "timestamp" = (unixepoch('now', 'subsecond') * 1000);


COMMIT;
''';

  @override
  String get definitionSql => '''BEGIN;

--
-- Class Address as table address
--
CREATE TABLE "address" (
    "id" INTEGER PRIMARY KEY,
    "street" TEXT NOT NULL,
    "inhabitantId" INTEGER,
    CONSTRAINT "address_fk_0" FOREIGN KEY ("inhabitantId") REFERENCES "citizen" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "inhabitant_index_idx" ON "address" ("inhabitantId");


--
-- Class Arena as table arena
--
CREATE TABLE "arena" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL
) STRICT;


--
-- Class Blocking as table blocking
--
CREATE TABLE "blocking" (
    "id" INTEGER PRIMARY KEY,
    "blockedId" INTEGER NOT NULL,
    "blockedById" INTEGER NOT NULL,
    CONSTRAINT "blocking_fk_0" FOREIGN KEY ("blockedId") REFERENCES "member" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "blocking_fk_1" FOREIGN KEY ("blockedById") REFERENCES "member" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "blocking_blocked_unique_idx" ON "blocking" ("blockedId", "blockedById");


--
-- Class Book as table book
--
CREATE TABLE "book" (
    "id" INTEGER PRIMARY KEY,
    "title" TEXT NOT NULL
) STRICT;


--
-- Class Cat as table cat
--
CREATE TABLE "cat" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "motherId" INTEGER,
    CONSTRAINT "cat_fk_0" FOREIGN KEY ("motherId") REFERENCES "cat" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
) STRICT;


--
-- Class Chapter as table chapter
--
CREATE TABLE "chapter" (
    "id" INTEGER PRIMARY KEY,
    "title" TEXT NOT NULL,
    "_bookChaptersBookId" INTEGER,
    CONSTRAINT "chapter_fk_0" FOREIGN KEY ("_bookChaptersBookId") REFERENCES "book" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
) STRICT;


--
-- Class Citizen as table citizen
--
CREATE TABLE "citizen" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "companyId" INTEGER NOT NULL,
    "oldCompanyId" INTEGER,
    CONSTRAINT "citizen_fk_0" FOREIGN KEY ("companyId") REFERENCES "company" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "citizen_fk_1" FOREIGN KEY ("oldCompanyId") REFERENCES "company" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
) STRICT;


--
-- Class City as table city
--
CREATE TABLE "city" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL
) STRICT;


--
-- Class Comment as table comment
--
CREATE TABLE "comment" (
    "id" INTEGER PRIMARY KEY,
    "description" TEXT NOT NULL,
    "orderId" INTEGER NOT NULL,
    CONSTRAINT "comment_fk_0" FOREIGN KEY ("orderId") REFERENCES "order" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
) STRICT;


--
-- Class Company as table company
--
CREATE TABLE "company" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "townId" INTEGER NOT NULL,
    CONSTRAINT "company_fk_0" FOREIGN KEY ("townId") REFERENCES "town" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
) STRICT;


--
-- Class Course as table course
--
CREATE TABLE "course" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL
) STRICT;


--
-- Class Customer as table customer
--
CREATE TABLE "customer" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL
) STRICT;


--
-- Class EmptyModelRelationItem as table empty_model_relation_item
--
CREATE TABLE "empty_model_relation_item" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "_relationEmptyModelItemsRelationEmptyModelId" INTEGER,
    CONSTRAINT "empty_model_relation_item_fk_0" FOREIGN KEY ("_relationEmptyModelItemsRelationEmptyModelId") REFERENCES "relation_empty_model" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
) STRICT;


--
-- Class EmptyModelWithTable as table empty_model_with_table
--
CREATE TABLE "empty_model_with_table" (
    "id" INTEGER PRIMARY KEY
) STRICT;


--
-- Class Enrollment as table enrollment
--
CREATE TABLE "enrollment" (
    "id" INTEGER PRIMARY KEY,
    "studentId" INTEGER NOT NULL,
    "courseId" INTEGER NOT NULL,
    CONSTRAINT "enrollment_fk_0" FOREIGN KEY ("studentId") REFERENCES "student" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "enrollment_fk_1" FOREIGN KEY ("courseId") REFERENCES "course" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "enrollment_index_idx" ON "enrollment" ("studentId", "courseId");


--
-- Class Member as table member
--
CREATE TABLE "member" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL
) STRICT;


--
-- Class ModelWithRequiredField as table model_with_required_field
--
CREATE TABLE "model_with_required_field" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "email" TEXT,
    "phone" TEXT
) STRICT;


--
-- Class ObjectFieldPersist as table object_field_persist
--
CREATE TABLE "object_field_persist" (
    "id" INTEGER PRIMARY KEY,
    "normal" TEXT NOT NULL
) STRICT;


--
-- Class Order as table order
--
CREATE TABLE "order" (
    "id" INTEGER PRIMARY KEY,
    "description" TEXT NOT NULL,
    "customerId" INTEGER NOT NULL,
    CONSTRAINT "order_fk_0" FOREIGN KEY ("customerId") REFERENCES "customer" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
) STRICT;


--
-- Class Organization as table organization
--
CREATE TABLE "organization" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "cityId" INTEGER,
    CONSTRAINT "organization_fk_0" FOREIGN KEY ("cityId") REFERENCES "city" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
) STRICT;


--
-- Class Person as table person
--
CREATE TABLE "person" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "organizationId" INTEGER,
    "_cityCitizensCityId" INTEGER,
    CONSTRAINT "person_fk_0" FOREIGN KEY ("organizationId") REFERENCES "organization" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "person_fk_1" FOREIGN KEY ("_cityCitizensCityId") REFERENCES "city" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
) STRICT;


--
-- Class Player as table player
--
CREATE TABLE "player" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "teamId" INTEGER,
    CONSTRAINT "player_fk_0" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
) STRICT;


--
-- Class Post as table post
--
CREATE TABLE "post" (
    "id" INTEGER PRIMARY KEY,
    "content" TEXT NOT NULL,
    "nextId" INTEGER,
    CONSTRAINT "post_fk_0" FOREIGN KEY ("nextId") REFERENCES "post" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "next_unique_idx" ON "post" ("nextId");


--
-- Class RelatedUniqueData as table related_unique_data
--
CREATE TABLE "related_unique_data" (
    "id" INTEGER PRIMARY KEY,
    "uniqueDataId" INTEGER NOT NULL,
    "number" INTEGER NOT NULL,
    CONSTRAINT "related_unique_data_fk_0" FOREIGN KEY ("uniqueDataId") REFERENCES "unique_data" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION
) STRICT;


--
-- Class RelationEmptyModel as table relation_empty_model
--
CREATE TABLE "relation_empty_model" (
    "id" INTEGER PRIMARY KEY
) STRICT;


--
-- Class SimpleData as table simple_data
--
CREATE TABLE "simple_data" (
    "id" INTEGER PRIMARY KEY,
    "num" INTEGER NOT NULL
) STRICT;


--
-- Class SimpleDateTime as table simple_date_time
--
CREATE TABLE "simple_date_time" (
    "id" INTEGER PRIMARY KEY,
    "dateTime" INTEGER NOT NULL
) STRICT;


--
-- Class Student as table student
--
CREATE TABLE "student" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL
) STRICT;


--
-- Class Team as table team
--
CREATE TABLE "team" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "arenaId" INTEGER,
    CONSTRAINT "team_fk_0" FOREIGN KEY ("arenaId") REFERENCES "arena" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "arena_index_idx" ON "team" ("arenaId");


--
-- Class Town as table town
--
CREATE TABLE "town" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "mayorId" INTEGER,
    CONSTRAINT "town_fk_0" FOREIGN KEY ("mayorId") REFERENCES "citizen" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
) STRICT;


--
-- Class Types as table types
--
CREATE TABLE "types" (
    "id" INTEGER PRIMARY KEY,
    "anInt" INTEGER,
    "aBool" INTEGER,
    "aDouble" REAL,
    "aDateTime" INTEGER,
    "aString" TEXT,
    "aByteData" BLOB,
    "aDuration" INTEGER,
    "aUuid" BLOB,
    "aUri" TEXT,
    "aBigInt" TEXT,
    "aVector" TEXT,
    "aHalfVector" TEXT,
    "aSparseVector" TEXT,
    "aBit" TEXT,
    "anEnum" INTEGER,
    "aStringifiedEnum" TEXT,
    "aList" TEXT,
    "aMap" TEXT,
    "aSet" TEXT,
    "aRecord" TEXT
) STRICT;


--
-- Class UniqueData as table unique_data
--
CREATE TABLE "unique_data" (
    "id" INTEGER PRIMARY KEY,
    "number" INTEGER NOT NULL,
    "email" TEXT NOT NULL
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "email_index_idx" ON "unique_data" ("email");


--
-- Class UniqueDataWithNonPersist as table unique_data_with_non_persist
--
CREATE TABLE "unique_data_with_non_persist" (
    "id" INTEGER PRIMARY KEY,
    "number" INTEGER NOT NULL,
    "email" TEXT NOT NULL
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "unique_email_idx" ON "unique_data_with_non_persist" ("email");


--
-- Class CloudStorageEntry as table serverpod_cloud_storage
--
CREATE TABLE "serverpod_cloud_storage" (
    "id" INTEGER PRIMARY KEY,
    "storageId" TEXT NOT NULL,
    "path" TEXT NOT NULL,
    "addedTime" INTEGER NOT NULL,
    "expiration" INTEGER,
    "byteData" BLOB NOT NULL,
    "verified" INTEGER NOT NULL
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "serverpod_cloud_storage_path_idx" ON "serverpod_cloud_storage" ("storageId", "path");
CREATE INDEX "serverpod_cloud_storage_expiration" ON "serverpod_cloud_storage" ("expiration");


--
-- Class CloudStorageDirectUploadEntry as table serverpod_cloud_storage_direct_upload
--
CREATE TABLE "serverpod_cloud_storage_direct_upload" (
    "id" INTEGER PRIMARY KEY,
    "storageId" TEXT NOT NULL,
    "path" TEXT NOT NULL,
    "expiration" INTEGER NOT NULL,
    "authKey" TEXT NOT NULL
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "serverpod_cloud_storage_direct_upload_storage_path" ON "serverpod_cloud_storage_direct_upload" ("storageId", "path");


--
-- Class FutureCallEntry as table serverpod_future_call
--
CREATE TABLE "serverpod_future_call" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "time" INTEGER NOT NULL,
    "serializedObject" TEXT,
    "serverId" TEXT NOT NULL,
    "identifier" TEXT,
    "scheduling" TEXT
) STRICT;

-- Indexes
CREATE INDEX "serverpod_future_call_time_idx" ON "serverpod_future_call" ("time");
CREATE INDEX "serverpod_future_call_serverId_idx" ON "serverpod_future_call" ("serverId");
CREATE INDEX "serverpod_future_call_identifier_idx" ON "serverpod_future_call" ("identifier");


--
-- Class FutureCallClaimEntry as table serverpod_future_call_claim
--
CREATE TABLE "serverpod_future_call_claim" (
    "id" INTEGER PRIMARY KEY,
    "futureCallId" INTEGER,
    "lastHeartbeatTime" INTEGER NOT NULL,
    CONSTRAINT "serverpod_future_call_claim_fk_0" FOREIGN KEY ("futureCallId") REFERENCES "serverpod_future_call" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "future_call_unique_idx" ON "serverpod_future_call_claim" ("futureCallId");


--
-- Class ServerHealthConnectionInfo as table serverpod_health_connection_info
--
CREATE TABLE "serverpod_health_connection_info" (
    "id" INTEGER PRIMARY KEY,
    "serverId" TEXT NOT NULL,
    "timestamp" INTEGER NOT NULL,
    "active" INTEGER NOT NULL,
    "closing" INTEGER NOT NULL,
    "idle" INTEGER NOT NULL,
    "granularity" INTEGER NOT NULL
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "serverpod_health_connection_info_timestamp_idx" ON "serverpod_health_connection_info" ("timestamp", "serverId", "granularity");


--
-- Class ServerHealthMetric as table serverpod_health_metric
--
CREATE TABLE "serverpod_health_metric" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "serverId" TEXT NOT NULL,
    "timestamp" INTEGER NOT NULL,
    "isHealthy" INTEGER NOT NULL,
    "value" REAL NOT NULL,
    "granularity" INTEGER NOT NULL
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "serverpod_health_metric_timestamp_idx" ON "serverpod_health_metric" ("timestamp", "serverId", "name", "granularity");


--
-- Class LogEntry as table serverpod_log
--
CREATE TABLE "serverpod_log" (
    "id" INTEGER PRIMARY KEY,
    "sessionLogId" INTEGER NOT NULL,
    "messageId" INTEGER,
    "reference" TEXT,
    "serverId" TEXT NOT NULL,
    "time" INTEGER NOT NULL,
    "logLevel" INTEGER NOT NULL,
    "message" TEXT NOT NULL,
    "error" TEXT,
    "stackTrace" TEXT,
    "order" INTEGER NOT NULL,
    CONSTRAINT "serverpod_log_fk_0" FOREIGN KEY ("sessionLogId") REFERENCES "serverpod_session_log" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
) STRICT;

-- Indexes
CREATE INDEX "serverpod_log_sessionLogId_idx" ON "serverpod_log" ("sessionLogId", "order");


--
-- Class MessageLogEntry as table serverpod_message_log
--
CREATE TABLE "serverpod_message_log" (
    "id" INTEGER PRIMARY KEY,
    "sessionLogId" INTEGER NOT NULL,
    "serverId" TEXT NOT NULL,
    "messageId" INTEGER NOT NULL,
    "endpoint" TEXT NOT NULL,
    "messageName" TEXT NOT NULL,
    "duration" REAL NOT NULL,
    "error" TEXT,
    "stackTrace" TEXT,
    "slow" INTEGER NOT NULL,
    "order" INTEGER NOT NULL,
    CONSTRAINT "serverpod_message_log_fk_0" FOREIGN KEY ("sessionLogId") REFERENCES "serverpod_session_log" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
) STRICT;

-- Indexes
CREATE INDEX "serverpod_message_log_sessionLogId_idx" ON "serverpod_message_log" ("sessionLogId", "order");


--
-- Class MethodInfo as table serverpod_method
--
CREATE TABLE "serverpod_method" (
    "id" INTEGER PRIMARY KEY,
    "endpoint" TEXT NOT NULL,
    "method" TEXT NOT NULL
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "serverpod_method_endpoint_method_idx" ON "serverpod_method" ("endpoint", "method");


--
-- Class DatabaseMigrationVersion as table serverpod_migrations
--
CREATE TABLE "serverpod_migrations" (
    "id" INTEGER PRIMARY KEY,
    "module" TEXT NOT NULL,
    "version" TEXT NOT NULL,
    "timestamp" INTEGER
) STRICT;

-- Indexes
CREATE UNIQUE INDEX "serverpod_migrations_ids" ON "serverpod_migrations" ("module");


--
-- Class QueryLogEntry as table serverpod_query_log
--
CREATE TABLE "serverpod_query_log" (
    "id" INTEGER PRIMARY KEY,
    "serverId" TEXT NOT NULL,
    "sessionLogId" INTEGER NOT NULL,
    "messageId" INTEGER,
    "query" TEXT NOT NULL,
    "duration" REAL NOT NULL,
    "numRows" INTEGER,
    "error" TEXT,
    "stackTrace" TEXT,
    "slow" INTEGER NOT NULL,
    "order" INTEGER NOT NULL,
    CONSTRAINT "serverpod_query_log_fk_0" FOREIGN KEY ("sessionLogId") REFERENCES "serverpod_session_log" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
) STRICT;

-- Indexes
CREATE INDEX "serverpod_query_log_sessionLogId_idx" ON "serverpod_query_log" ("sessionLogId", "order");


--
-- Class ReadWriteTestEntry as table serverpod_readwrite_test
--
CREATE TABLE "serverpod_readwrite_test" (
    "id" INTEGER PRIMARY KEY,
    "number" INTEGER NOT NULL
) STRICT;


--
-- Class RuntimeSettings as table serverpod_runtime_settings
--
CREATE TABLE "serverpod_runtime_settings" (
    "id" INTEGER PRIMARY KEY,
    "logSettings" TEXT NOT NULL,
    "logSettingsOverrides" TEXT NOT NULL,
    "logServiceCalls" INTEGER NOT NULL,
    "logMalformedCalls" INTEGER NOT NULL
) STRICT;


--
-- Class SessionLogEntry as table serverpod_session_log
--
CREATE TABLE "serverpod_session_log" (
    "id" INTEGER PRIMARY KEY,
    "serverId" TEXT NOT NULL,
    "time" INTEGER NOT NULL,
    "module" TEXT,
    "endpoint" TEXT,
    "method" TEXT,
    "duration" REAL,
    "numQueries" INTEGER,
    "slow" INTEGER,
    "error" TEXT,
    "stackTrace" TEXT,
    "authenticatedUserId" INTEGER,
    "userId" TEXT,
    "isOpen" INTEGER,
    "touched" INTEGER NOT NULL
) STRICT;

-- Indexes
CREATE INDEX "serverpod_session_log_serverid_idx" ON "serverpod_session_log" ("serverId");
CREATE INDEX "serverpod_session_log_time_idx" ON "serverpod_session_log" ("time");
CREATE INDEX "serverpod_session_log_touched_idx" ON "serverpod_session_log" ("touched");
CREATE INDEX "serverpod_session_log_isopen_idx" ON "serverpod_session_log" ("isOpen");


--
-- STORE COLUMN TYPES FOR MIGRATIONS
--
DROP TABLE IF EXISTS "serverpod_sqlite_schema";

CREATE TABLE "serverpod_sqlite_schema" (
    "table_name" TEXT NOT NULL,
    "column_name" TEXT NOT NULL,
    "column_type" TEXT NOT NULL,
    "column_vector_dimension" INTEGER,
    PRIMARY KEY ("table_name", "column_name")
);

INSERT INTO "serverpod_sqlite_schema" VALUES
    ('simple_date_time', 'dateTime', 'timestampWithoutTimeZone', NULL),
    ('types', 'aBool', 'boolean', NULL),
    ('types', 'aDateTime', 'timestampWithoutTimeZone', NULL),
    ('types', 'aUuid', 'uuid', NULL),
    ('types', 'aVector', 'vector', 3),
    ('types', 'aHalfVector', 'halfvec', 3),
    ('types', 'aSparseVector', 'sparsevec', 3),
    ('types', 'aBit', 'bit', 3),
    ('types', 'aList', 'json', NULL),
    ('types', 'aMap', 'json', NULL),
    ('types', 'aSet', 'json', NULL),
    ('types', 'aRecord', 'json', NULL),
    ('serverpod_cloud_storage', 'addedTime', 'timestampWithoutTimeZone', NULL),
    ('serverpod_cloud_storage', 'expiration', 'timestampWithoutTimeZone', NULL),
    ('serverpod_cloud_storage', 'verified', 'boolean', NULL),
    ('serverpod_cloud_storage_direct_upload', 'expiration', 'timestampWithoutTimeZone', NULL),
    ('serverpod_future_call', 'time', 'timestampWithoutTimeZone', NULL),
    ('serverpod_future_call', 'scheduling', 'json', NULL),
    ('serverpod_future_call_claim', 'lastHeartbeatTime', 'timestampWithoutTimeZone', NULL),
    ('serverpod_health_connection_info', 'timestamp', 'timestampWithoutTimeZone', NULL),
    ('serverpod_health_metric', 'timestamp', 'timestampWithoutTimeZone', NULL),
    ('serverpod_health_metric', 'isHealthy', 'boolean', NULL),
    ('serverpod_log', 'time', 'timestampWithoutTimeZone', NULL),
    ('serverpod_message_log', 'slow', 'boolean', NULL),
    ('serverpod_migrations', 'timestamp', 'timestampWithoutTimeZone', NULL),
    ('serverpod_query_log', 'slow', 'boolean', NULL),
    ('serverpod_runtime_settings', 'logSettings', 'json', NULL),
    ('serverpod_runtime_settings', 'logSettingsOverrides', 'json', NULL),
    ('serverpod_runtime_settings', 'logServiceCalls', 'boolean', NULL),
    ('serverpod_runtime_settings', 'logMalformedCalls', 'boolean', NULL),
    ('serverpod_session_log', 'time', 'timestampWithoutTimeZone', NULL),
    ('serverpod_session_log', 'slow', 'boolean', NULL),
    ('serverpod_session_log', 'isOpen', 'boolean', NULL),
    ('serverpod_session_log', 'touched', 'timestampWithoutTimeZone', NULL);

--
-- MIGRATION VERSION FOR serverpod_test_sqlite
--
INSERT INTO "serverpod_migrations" ("module", "version", "timestamp")
    VALUES ('serverpod_test_sqlite', '20260425031610501', (unixepoch('now', 'subsecond') * 1000))
    ON CONFLICT ("module")
    DO UPDATE SET "version" = '20260425031610501', "timestamp" = (unixepoch('now', 'subsecond') * 1000);

--
-- MIGRATION VERSION FOR serverpod
--
INSERT INTO "serverpod_migrations" ("module", "version", "timestamp")
    VALUES ('serverpod', '20260416151914983-insights-perf', (unixepoch('now', 'subsecond') * 1000))
    ON CONFLICT ("module")
    DO UPDATE SET "version" = '20260416151914983-insights-perf', "timestamp" = (unixepoch('now', 'subsecond') * 1000);


COMMIT;
''';
}
