import 'package:flutter/material.dart';

import '../../common/text_formatters.dart';
import '../../common/widgets/buttons/action_button.dart';
import '../../common/widgets/gaps.dart';
import '../../common/widgets/verification_code.dart';
import '../email_auth_controller.dart';
import 'widgets/back_to_sign_in_button.dart';
import 'widgets/form_standard_layout.dart';
import '../../common/widgets/buttons/resend_code_button.dart';

// Export types used in the [VerificationCodeConfig] class.
export 'package:flutter/services.dart' show TextInputType;
export '../../common/text_formatters.dart' show LetterCase;

/// Pattern with the default server-side characters in the verification code.
///
/// The default is to generate codes with digits from [1-9].
final _defaultAllowedCharacters = RegExp(r'[1-9]');

/// Email verification form widget.
///
/// Displays a verification code input field for users to validate a request.
class VerificationForm extends StatefulWidget {
  /// The controller that manages authentication state and logic.
  final EmailAuthController controller;

  /// Callback to call when verification is completed.
  ///
  /// Should navigate to the next screen.
  final VoidCallback onCompleted;

  /// The title of the form.
  final String title;

  /// Optional message text to display.
  ///
  /// If not provided, defaults to the registration verification message.
  final String? messageText;

  /// Optional label for the verify button.
  ///
  /// If not provided, defaults to 'Verify'.
  final String? verifyButtonLabel;

  /// Configuration for the verification code input.
  final VerificationCodeConfig verificationCodeConfig;

  /// Creates a [VerificationForm] widget.
  const VerificationForm({
    required this.title,
    required this.controller,
    required this.onCompleted,
    required this.verificationCodeConfig,
    this.messageText,
    this.verifyButtonLabel,
    super.key,
  });

  @override
  State<VerificationForm> createState() => _VerificationFormState();
}

class _VerificationFormState extends State<VerificationForm> {
  late final FocusNode focusNode;

  EmailAuthController get controller => widget.controller;

  @override
  void initState() {
    super.initState();
    focusNode = FocusNode();

    controller.addListener(_onControllerStateChanged);
  }

  /// Automatically focus the verification code input when an error occurs for
  /// the user to correct it.
  void _onControllerStateChanged() {
    if (!mounted) return;
    if (controller.state == EmailAuthState.error) {
      focusNode.requestFocus();
    }
  }

  @override
  void dispose() {
    controller.removeListener(_onControllerStateChanged);
    focusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final config = widget.verificationCodeConfig;

    return FormStandardLayout(
      title: widget.title,
      content: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Text(
            widget.messageText ??
                'A verification email has been sent. Please check your email '
                    'and enter the verification code below.',
            style: Theme.of(context).textTheme.bodyMedium,
            textAlign: TextAlign.left,
          ),
          smallGap,
          VerificationCodeInput(
            focusNode: focusNode,
            verificationCodeController: controller.verificationCodeController,
            onCompleted: widget.onCompleted,
            isLoading: controller.isLoading,
            length: config.length,
            keyboardType: config.keyboardType,
            allowedLetterCase: config.allowedLetterCase,
            allowedCharactersPattern:
                config.allowedCharactersPattern ?? _defaultAllowedCharacters,
          ),
          ResendCodeButton(
            onResendPressed: controller.resendVerificationCode,
            countdownDuration: config.resendCountdownDuration,
          ),
        ],
      ),
      actionButton: ActionButton(
        onPressed: widget.onCompleted,
        label: widget.verifyButtonLabel ?? 'Verify',
        isLoading: controller.isLoading,
      ),
      bottomText: BackToSignInButton(controller: controller),
    );
  }
}

/// Configuration for verification code input.
class VerificationCodeConfig {
  /// The length of the verification code.
  ///
  /// Make sure to match the length of the code generated by the server.
  final int length;

  /// The keyboard type to use for the verification code input.
  final TextInputType keyboardType;

  /// The case of letters allowed in the verification code input.
  final LetterCase allowedLetterCase;

  /// The duration of the countdown timer for resending the code.
  final Duration resendCountdownDuration;

  /// A pattern of the allowed characters in the verification code input.
  ///
  /// This value must be synchronized with the server-side configuration. If
  /// not provided, will restrict to the default configuration of the server,
  /// which allows only lowercase alphanumeric characters and excludes visually
  /// similar characters like 0, O, 1, l.
  final Pattern? allowedCharactersPattern;

  /// Creates a [VerificationCodeConfig] with the given parameters.
  const VerificationCodeConfig({
    this.length = 8,
    this.keyboardType = TextInputType.number,
    this.allowedLetterCase = LetterCase.lowercase,
    this.resendCountdownDuration = const Duration(minutes: 1),
    this.allowedCharactersPattern,
  });

  /// Creates a [VerificationCodeConfig] to use with numbers only.
  factory VerificationCodeConfig.numbersOnly({required int length}) =>
      VerificationCodeConfig(
        length: length,
        keyboardType: TextInputType.number,
        allowedLetterCase: LetterCase.lowercase,
        allowedCharactersPattern: RegExp(r'[0-9]'),
      );
}
