include: package:serverpod_lints/public.yaml

analyzer:
  exclude:
    - lib/src/generated/**
    - test/test_tools/serverpod_test_tools.dart

linter:
  rules:
    prefer_initializing_formals: false

formatter:
  trailing_commas: preserve
