#!/bin/bash

# Variables for dynamic configuration
USERNAME=ec2-user
WORKDIR=/home/$USERNAME

# Write the systemd unit file
cat > /lib/systemd/system/serverpod.service << EOF
[Unit]
Description=Serverpod server
After=network-online.target

[Service]
User=$USERNAME
WorkingDirectory=$WORKDIR
ExecStart=$WORKDIR/serverpod/active/chat_server/aws/scripts/run_serverpod
Restart=always

[Install]
WantedBy=network-online.target
EOF

# Reload systemd, enable and start the service
systemctl daemon-reload
systemctl enable serverpod.service
systemctl start serverpod.service
