name: serverpod_auth_email_client
description: Serverpod email authentication endpoint client module.
version: 2.8.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  serverpod_client: 2.8.0

dependency_overrides:
  serverpod_client:
    path: ../../../../packages/serverpod_client
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
