name: serverpod_relic_helpers
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.2.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  async: ^2.5.0
  collection: ^1.15.0
  http_parser: ^4.0.2
  path: ^1.8.0
  stack_trace: ^1.10.0
  stream_channel: ^2.1.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  http: '>=0.13.0 <2.0.0'
  test: ^1.16.0
