apiServer:
  port: 8080
  publicHost: "localhost"
  publicPort: 8080
  publicScheme: "http"

database:
  host: localhost
  port: 8090
  name: serverpod_test
  user: postgres

sessionLogs:
  persistentEnabled: true
  consoleEnabled: true