name: serverpod_auth_passkey_account_server
description: Starting point for a Serverpod module.

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  serverpod: 2.9.1

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  test: '^1.24.2'
  serverpod_test: 2.9.1

dependency_overrides: 
  serverpod: 
    path: /Volumes/CaseSensititve/SourcesCS/serverpod/packages/serverpod 
  serverpod_serialization: 
    path: /Volumes/CaseSensititve/SourcesCS/serverpod/packages/serverpod_serialization 
  serverpod_shared: 
    path: /Volumes/CaseSensititve/SourcesCS/serverpod/packages/serverpod_shared 
  serverpod_test: 
    path: /Volumes/CaseSensititve/SourcesCS/serverpod/packages/serverpod_test 
  serverpod_lints: 
    path: /Volumes/CaseSensititve/SourcesCS/serverpod/packages/serverpod_lints 
