name: serverpod_auth_email_account_client
description: Serverpod email authentication core client module.

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  serverpod_auth_user_client: 2.8.0
  serverpod_client: 2.8.0

dependency_overrides:
  serverpod_auth_user_client:
    path: ../../serverpod_auth_user/serverpod_auth_user_client
  serverpod_client:
    path: ../../../../packages/serverpod_client
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
