name: serverpod_auth_backwards_compatibility_client
description: Serverpod authentication backwards compatibility client module.

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  serverpod_auth_email_account_client: 2.9.1
  serverpod_auth_session_client: 2.9.1
  serverpod_auth_user_client: 2.9.1
  serverpod_client: 2.9.1

dependency_overrides:
  serverpod_auth_email_account_client:
    path: ../../serverpod_auth_email_account/serverpod_auth_email_account_client
  serverpod_auth_session_client:
    path: ../../serverpod_auth_session/serverpod_auth_session_client
  serverpod_auth_user_client:
    path: ../../serverpod_auth_user/serverpod_auth_user_client
  serverpod_client:
    path: ../../../../packages/serverpod_client
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
