name: serverpod_auth_api_tokens_server
description: Serverpod authentication API token server module.
version: SERVERPOD_VERSION
repository: https://github.com/serverpod/serverpod

environment:
  sdk: DART_VERSION

dependencies:
  serverpod: SERVERPOD_VERSION

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  test: '^1.24.2'
  serverpod_test: SERVERPOD_VERSION

dependency_overrides:
  serverpod:
    path: ../../../../packages/serverpod
  serverpod_auth_user_server:
    path: ../../../new_serverpod_auth/serverpod_auth_user/serverpod_auth_user_server
  serverpod_lints:
    path: ../../../../packages/serverpod_lints
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
  serverpod_shared:
    path: ../../../../packages/serverpod_shared
  serverpod_test:
    path: ../../../../packages/serverpod_test
