name: serverpod_auth_api_tokens_client
description: Serverpod authentication API token client module.
version: 2.8.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  serverpod_client: 2.8.0

dependency_overrides:
  serverpod_auth_user_client:
    path: ../../serverpod_auth_user/serverpod_auth_user_client
  serverpod_client:
    path: ../../../../packages/serverpod_client
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
