version: '3.7'

services:
  # Test services
  postgres_test:
    image: postgres:16.3
    ports:
      - '9090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: projectname_test
      POSTGRES_PASSWORD: "DB_TEST_PASSWORD"
    volumes:
      - projectname_test_data:/var/lib/postgresql/data
  redis_test:
    image: redis:6.2.6
    ports:
      - '9091:6379'
    command: redis-server --requirepass "REDIS_TEST_PASSWORD"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  projectname_test_data:
