import 'dart:io';

import 'package:path/path.dart' as path;
import 'package:serverpod/protocol.dart';
import 'package:serverpod_serialization/serverpod_serialization.dart';
import 'package:serverpod/src/database/migrations/migration_artifacts.dart';
import 'package:serverpod_shared/serverpod_shared.dart';

/// Stores migration artifacts using the current file-system based format.
class FileSystemMigrationArtifactStore implements MigrationArtifactStore {
  /// Creates a new file system migration artifact store.
  FileSystemMigrationArtifactStore({
    required Directory projectDirectory,
  }) : _projectDirectory = projectDirectory;

  final Directory _projectDirectory;

  static const _migrationRegistryHeader = '''
### AUTOMATICALLY GENERATED DO NOT MODIFY
###
### This file is generated by Serverpod when creating a migration, do not modify it
### manually. If a collision is detected in this file when doing a code merge, resolve
### the conflict by removing and recreating the conflicting migration.

''';

  @override
  Future<List<String>> listVersions() async {
    var migrationsDirectory = MigrationConstants.migrationsBaseDirectory(
      _projectDirectory,
    );

    if (!await migrationsDirectory.exists()) {
      return [];
    }

    return await migrationsDirectory
          .list()
          .where((entity) => entity is Directory)
          .cast<Directory>()
          .map((directory) => path.basename(directory.path))
          .toList()
      ..sort();
  }

  @override
  Future<MigrationVersionArtifacts?> readVersion(String version) async {
    var versionDirectory = MigrationConstants.migrationVersionDirectory(
      _projectDirectory,
      version,
    );
    if (!await versionDirectory.exists()) {
      return null;
    }

    var definition = await _readRequiredProtocolFile<DatabaseDefinition>(
      MigrationConstants.databaseDefinitionJSONPath(_projectDirectory, version),
    );

    return MigrationVersionArtifacts(
      version: version,
      definitionSql: await _readRequiredFile(
        MigrationConstants.databaseDefinitionSQLPath(
          _projectDirectory,
          version,
        ),
      ),
      migrationSql: await _readRequiredFile(
        MigrationConstants.databaseMigrationSQLPath(_projectDirectory, version),
      ),
      definition: definition,
      projectDefinition: await _readRequiredProtocolFile<DatabaseDefinition>(
        MigrationConstants.databaseDefinitionProjectJSONPath(
          _projectDirectory,
          version,
        ),
      ),
      migration: await _readRequiredProtocolFile<DatabaseMigration>(
        MigrationConstants.databaseMigrationJSONPath(
          _projectDirectory,
          version,
        ),
      ),
    );
  }

  @override
  Future<void> writeVersion(MigrationVersionArtifacts artifacts) async {
    var versionDirectory = MigrationConstants.migrationVersionDirectory(
      _projectDirectory,
      artifacts.version,
    );
    if (await versionDirectory.exists()) {
      throw MigrationVersionAlreadyExistsException(
        directoryPath: versionDirectory.path,
      );
    }
    await versionDirectory.create(recursive: true);

    await _writeFile(
      MigrationConstants.databaseDefinitionProjectJSONPath(
        _projectDirectory,
        artifacts.version,
      ),
      _encodeProtocolObject(artifacts.projectDefinition),
    );
    await _writeFile(
      MigrationConstants.databaseDefinitionJSONPath(
        _projectDirectory,
        artifacts.version,
      ),
      _encodeProtocolObject(artifacts.definition),
    );
    await _writeFile(
      MigrationConstants.databaseDefinitionSQLPath(
        _projectDirectory,
        artifacts.version,
      ),
      artifacts.definitionSql,
    );
    await _writeFile(
      MigrationConstants.databaseMigrationJSONPath(
        _projectDirectory,
        artifacts.version,
      ),
      _encodeProtocolObject(artifacts.migration),
    );
    await _writeFile(
      MigrationConstants.databaseMigrationSQLPath(
        _projectDirectory,
        artifacts.version,
      ),
      artifacts.migrationSql,
    );
  }

  @override
  Future<void> writeVersionRegistry(List<String> versions) async {
    var registryFile = File(
      path.join(
        MigrationConstants.migrationsBaseDirectory(_projectDirectory).path,
        'migration_registry.txt',
      ),
    );

    var contents = StringBuffer(_migrationRegistryHeader);
    for (var version in versions) {
      contents.writeln(version);
    }

    await registryFile.parent.create(recursive: true);
    await registryFile.writeAsString(contents.toString());
  }

  @override
  Future<RepairMigration?> readRepairMigration() async {
    var repairMigrationDirectory = MigrationConstants.repairMigrationDirectory(
      _projectDirectory,
    );
    if (!await repairMigrationDirectory.exists()) {
      return null;
    }

    var repairMigrationFiles = await repairMigrationDirectory
        .list()
        .where((entity) => entity is File)
        .cast<File>()
        .where((file) => path.basename(file.path).endsWith('.sql'))
        .toList();

    if (repairMigrationFiles.isEmpty) {
      return null;
    }

    var migrationSqlFile = repairMigrationFiles.single;
    return RepairMigration(
      version: path.basename(migrationSqlFile.path).split('.').first,
      migrationSql: await migrationSqlFile.readAsString(),
    );
  }

  @override
  Future<void> writeRepairMigration(RepairMigration repairMigration) async {
    try {
      var repairMigrationDirectory =
          MigrationConstants.repairMigrationDirectory(
            _projectDirectory,
          );
      if (await repairMigrationDirectory.exists()) {
        await repairMigrationDirectory.delete(recursive: true);
      }
      await repairMigrationDirectory.create(recursive: true);

      var repairMigrationFile = File(
        path.join(
          repairMigrationDirectory.path,
          '${repairMigration.version}.sql',
        ),
      );
      await repairMigrationFile.writeAsString(repairMigration.migrationSql);
    } catch (e) {
      throw MigrationRepairWriteException(exception: e.toString());
    }
  }

  static Future<String?> _readFileIfExists(File file) async {
    if (!await file.exists()) {
      return null;
    }

    return file.readAsString();
  }

  static Future<String> _readRequiredFile(File file) async {
    var contents = await _readFileIfExists(file);
    if (contents == null) {
      throw Exception('Required migration artifact is missing: ${file.path}');
    }
    return contents;
  }

  static Future<T> _readRequiredProtocolFile<T>(File file) async {
    var contents = await _readRequiredFile(file);
    return Protocol().decode<T>(contents);
  }

  static Future<void> _writeFile(File file, String contents) async {
    await file.writeAsString(contents);
  }

  static String _encodeProtocolObject<T>(T value) {
    return SerializationManager.encode(value, formatted: true);
  }
}
