name: _
publish_to: none

environment:
  sdk: '^3.8.0'

workspace:
  - mytest_client
  - mytest_server
  - mytest_flutter

dependency_overrides: 
  serverpod: 
    git:
      url: https://github.com/Crazelu/serverpod.git
      ref: feat/reliable-future-call-execution-local
      path: packages/serverpod 
    # path: /Users/crazelu/works/serverpod/serverpod/packages/serverpod 
  serverpod_database: 
    git:
      url: https://github.com/Crazelu/serverpod.git
      ref: feat/reliable-future-call-execution-local
      path: packages/serverpod_database 
    # path: /Users/crazelu/works/serverpod/serverpod/packages/serverpod_database 
  serverpod_serialization: 
    git:
      url: https://github.com/Crazelu/serverpod.git
      ref: feat/reliable-future-call-execution-local
      path: packages/serverpod_serialization 
    # path: /Users/crazelu/works/serverpod/serverpod/packages/serverpod_serialization 
  serverpod_shared: 
    git:
      url: https://github.com/Crazelu/serverpod.git
      ref: feat/reliable-future-call-execution-local
      path: packages/serverpod_shared 
    # path: /Users/crazelu/works/serverpod/serverpod/packages/serverpod_shared 
  serverpod_test: 
    git:
      url: https://github.com/Crazelu/serverpod.git
      ref: feat/reliable-future-call-execution-local
      path: packages/serverpod_test 
    # path: /Users/crazelu/works/serverpod/serverpod/packages/serverpod_test 
  serverpod_lints: 
    git:
      url: https://github.com/Crazelu/serverpod.git
      ref: feat/reliable-future-call-execution-local
      path: packages/serverpod_lints 
    # path: /Users/crazelu/works/serverpod/serverpod/packages/serverpod_lints 
  serverpod_client: 
    git:
      url: https://github.com/Crazelu/serverpod.git
      ref: feat/reliable-future-call-execution-local
      path: packages/serverpod_client 
    # path: /Users/crazelu/works/serverpod/serverpod/packages/serverpod_client 
  serverpod_flutter: 
    git:
      url: https://github.com/Crazelu/serverpod.git
      ref: feat/reliable-future-call-execution-local
      path: packages/serverpod_flutter 
    # path: /Users/crazelu/works/serverpod/serverpod/packages/serverpod_flutter 
  serverpod_auth_idp_server:
    git:
      url: https://github.com/Crazelu/serverpod.git
      ref: feat/reliable-future-call-execution-local
      path: modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server
    # path: /Users/crazelu/works/serverpod/serverpod/modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_server
  serverpod_auth_core_server:
    git:
      url: https://github.com/Crazelu/serverpod.git
      ref: feat/reliable-future-call-execution-local
      path: modules/serverpod_auth/serverpod_auth_core/serverpod_auth_core_server
    # path: /Users/crazelu/works/serverpod/serverpod/modules/serverpod_auth/serverpod_auth_core/serverpod_auth_core_server
  flutter_secure_storage: ^10.0.0
  serverpod_auth_idp_flutter:
    git:
      url: https://github.com/Crazelu/serverpod.git
      ref: feat/reliable-future-call-execution-local
      path: modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_flutter
    # path: /Users/crazelu/works/serverpod/serverpod/modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_flutter
  serverpod_auth_core_client:
    git:
      url: https://github.com/Crazelu/serverpod.git
      ref: feat/reliable-future-call-execution-local
      path: modules/serverpod_auth/serverpod_auth_core/serverpod_auth_core_client
    # path: /Users/crazelu/works/serverpod/serverpod/modules/serverpod_auth/serverpod_auth_core/serverpod_auth_core_client
  serverpod_auth_core_flutter:
    git:
      url: https://github.com/Crazelu/serverpod.git
      ref: feat/reliable-future-call-execution-local
      path: modules/serverpod_auth/serverpod_auth_core/serverpod_auth_core_flutter 
    # path: /Users/crazelu/works/serverpod/serverpod/modules/serverpod_auth/serverpod_auth_core/serverpod_auth_core_flutter
  serverpod_auth_idp_client:
    git:
      url: https://github.com/Crazelu/serverpod.git
      ref: feat/reliable-future-call-execution-local
      path: modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_client
    # path: /Users/crazelu/works/serverpod/serverpod/modules/serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_client
