name: serverpod_auth_email_server
description: Starting point for a Serverpod module.
version: 2.4.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  serverpod: 2.4.0
  serverpod_auth_server: 2.4.0
  email_validator: ">=2.1.17 <4.0.0"
  pointycastle: ^3.7.4
  crypto: ^3.0.2

dev_dependencies:
  lints: ">=3.0.0 <6.0.0"
  test: "^1.24.2"
  serverpod_test: 2.4.0

dependency_overrides:
  serverpod:
    path: ../../../../packages/serverpod
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
  serverpod_shared:
    path: ../../../../packages/serverpod_shared
  serverpod_auth_server:
    path: ../../serverpod_auth_server
  serverpod_test:
    path: ../../../../packages/serverpod_test
  serverpod_lints:
    path: ../../../../packages/serverpod_lints
