import 'dart:async';

import 'package:email_validator/email_validator.dart';
import 'package:serverpod/serverpod.dart';

import '../../../../../core.dart';
import '../../../utils/get_passwords_extension.dart';
import '../../email/business/email_idp_config.dart'
    show AfterAccountCreatedFunction;
import '../../email/util/default_code_generators.dart';
import 'email_passwordless_idp.dart';

export '../../email/business/email_idp_config.dart'
    show AfterAccountCreatedFunction;
export '../../email/util/default_code_generators.dart';

/// Function for sending out the verification code of a login request.
///
/// Used both for [EmailPasswordlessIdpConfig.sendSignUpVerificationCode] and
/// [EmailPasswordlessIdpConfig.sendSignInVerificationCode].
///
/// Sending is best-effort: an exception thrown by the function is logged and
/// never reported to the caller of `startLogin`, so that a failure can not be
/// used to find out whether an account exists for an email address.
typedef SendPasswordlessLoginVerificationCodeFunction =
    FutureOr<void> Function(
      Session session, {
      required String email,

      /// The ID of the login request that the code belongs to.
      required UuidValue loginRequestId,

      /// The code that was generated by
      /// [EmailPasswordlessIdpConfig.loginVerificationCodeGenerator] to verify
      /// this login request.
      required String verificationCode,
      required Transaction? transaction,
    });

/// Function to be called before a new account is created on the first
/// successful verification of an unknown email address.
///
/// Throw an exception to reject the sign-up, for example if the email address
/// belongs to a domain that is not allowed to register, or if the user has not
/// accepted the terms and conditions. The exception is propagated to the
/// caller of `finishLogin` unchanged, and no account is created.
///
/// Note that the verification code has already been consumed when this
/// function runs, so the user has to request a new code after a rejection.
typedef BeforePasswordlessAccountCreatedFunction =
    FutureOr<void> Function(
      Session session, {
      required String email,
      required Transaction? transaction,
    });

/// Function to be called after a successful passwordless login, right before
/// the authentication token is issued.
///
/// Throw an exception to reject the login. Because the function runs in the
/// same transaction as the issuing of the token, a rejection also rolls back
/// the account creation of a first login.
typedef AfterPasswordlessLoginFunction =
    FutureOr<void> Function(
      Session session, {
      required String email,
      required UuidValue authUserId,
      required UuidValue emailAccountId,

      /// Whether the account was created by this login.
      required bool accountCreated,
      required Transaction? transaction,
    });

/// Function to be called to check whether a (normalized) email address is
/// acceptable.
typedef EmailValidationFunction = bool Function(String email);

/// The default email validation, which accepts syntactically valid email
/// addresses.
bool defaultEmailValidationFunction(final String email) =>
    EmailValidator.validate(email);

/// {@template email_passwordless_idp_config}
/// Configuration options for the passwordless email identity provider.
///
/// With this provider a user logs in by receiving a short verification code in
/// their mailbox, and proves possession of the mailbox by entering it. No
/// password is involved. See https://github.com/serverpod/serverpod/issues/2100.
///
/// Accounts are stored as `EmailAccount`s, the same ones as used by the email
/// and password identity provider, but with an empty password hash. An existing
/// account (with or without a password) can log in with a code. Be aware that
/// possession of the mailbox is then enough to log in, which is the same trust
/// model as the password reset of the email and password identity provider.
/// If accounts can exist for email addresses that their owner never verified
/// (for example imported accounts), make sure that this is acceptable.
///
/// The two senders, [sendSignUpVerificationCode] and
/// [sendSignInVerificationCode], make it possible to word the emails
/// differently for users that are about to create an account and users that
/// already have one.
/// {@endtemplate}
class EmailPasswordlessIdpConfig
    extends IdentityProviderBuilder<EmailPasswordlessIdp> {
  /// The pepper used for hashing verification codes.
  ///
  /// To rotate peppers without invalidating pending login requests, use
  /// [fallbackSecretHashPeppers].
  final String secretHashPepper;

  /// Optional fallback peppers for validating verification codes created with
  /// previous peppers.
  ///
  /// When rotating peppers, add old peppers to this list to allow pending login
  /// requests to continue working. The system will try [secretHashPepper]
  /// first, then each fallback pepper in order until a match is found.
  ///
  /// This is optional and defaults to an empty list.
  final List<String> fallbackSecretHashPeppers;

  /// The length in bytes of the random salt generated for each hashed code.
  ///
  /// Must be at least 8, the shortest salt Argon2 accepts.
  /// Defaults to 16.
  final int secretHashSaltLength;

  /// The time for a login verification code to be valid.
  ///
  /// Default is 10 minutes.
  final Duration loginVerificationCodeLifetime;

  /// How many attempts are permitted for a login verification code (during the
  /// [loginVerificationCodeLifetime] window).
  ///
  /// Defaults to 3.
  final int loginVerificationCodeAllowedAttempts;

  /// Function returning the login verification code.
  ///
  /// By default this is a 6 digit code (`0`-`9`).
  ///
  /// If the codes are sent through the Serverpod Cloud email service, they must
  /// consist of 1-16 alphanumeric characters.
  final String Function() loginVerificationCodeGenerator;

  /// The maximum number of failed code verifications for the same email, across
  /// all of its login requests.
  ///
  /// Successful logins clear the count.
  ///
  /// Defaults to allowing up to 5 attempts for a sliding 5 minutes. Beyond
  /// that, verification attempts are rejected without checking the code.
  final RateLimit failedLoginRateLimit;

  /// The maximum number of login requests (calls to `startLogin`) for the same
  /// email.
  ///
  /// Defaults to allowing up to 5 requests for a sliding 5 minutes.
  final RateLimit loginRequestRateLimit;

  /// The minimum time between two emails with a code to the same address.
  ///
  /// While a login request is younger than this, `startLogin` does not send a
  /// new code and does not replace the pending request, so the pending code
  /// stays valid and an attacker can not keep invalidating the code of a user.
  ///
  /// Defaults to 60 seconds.
  final Duration resendCooldown;

  /// Whether an unknown email address is signed up on the first successful
  /// verification of a code.
  ///
  /// If `false`, no code is sent for unknown email addresses, and `startLogin`
  /// returns a request ID that can never be completed. This is done to not
  /// reveal whether an account exists. Defaults to `true`.
  final bool allowSignUp;

  /// Callback to send the code for an email address without an account.
  ///
  /// Called when [allowSignUp] is `true` and logging in will create an account.
  final SendPasswordlessLoginVerificationCodeFunction
  sendSignUpVerificationCode;

  /// Callback to send the code for an email address with an existing account.
  final SendPasswordlessLoginVerificationCodeFunction
  sendSignInVerificationCode;

  /// Function to check whether an email address is acceptable.
  ///
  /// It receives the email address after normalization (trimmed and in lower
  /// case). Defaults to [defaultEmailValidationFunction].
  final EmailValidationFunction validateEmail;

  /// Callback to be invoked before a new account is created.
  ///
  /// This is the place to enforce a sign-up policy, see
  /// [BeforePasswordlessAccountCreatedFunction].
  final BeforePasswordlessAccountCreatedFunction? onBeforeAccountCreated;

  /// Callback to be invoked after a new account has been created.
  ///
  /// Runs in the same transaction as the account creation.
  final AfterAccountCreatedFunction? onAfterAccountCreated;

  /// Callback to be invoked after each successful login, before the token is
  /// issued.
  ///
  /// This can be used for example to revoke other sessions of the user, as the
  /// passwordless identity provider does not revoke any sessions by itself.
  final AfterPasswordlessLoginFunction? onAfterLogin;

  /// Creates a new passwordless email identity provider configuration.
  const EmailPasswordlessIdpConfig({
    required this.secretHashPepper,
    required this.sendSignUpVerificationCode,
    required this.sendSignInVerificationCode,
    this.fallbackSecretHashPeppers = const [],
    this.secretHashSaltLength = 16,
    this.loginVerificationCodeLifetime = const Duration(minutes: 10),
    this.loginVerificationCodeAllowedAttempts = 3,
    this.loginVerificationCodeGenerator =
        defaultSixDigitVerificationCodeGenerator,
    this.failedLoginRateLimit = const RateLimit(
      maxAttempts: 5,
      timeframe: Duration(minutes: 5),
    ),
    this.loginRequestRateLimit = const RateLimit(
      maxAttempts: 5,
      timeframe: Duration(minutes: 5),
    ),
    this.resendCooldown = const Duration(seconds: 60),
    this.allowSignUp = true,
    this.validateEmail = defaultEmailValidationFunction,
    this.onBeforeAccountCreated,
    this.onAfterAccountCreated,
    this.onAfterLogin,
  });

  @override
  EmailPasswordlessIdp build({
    required final TokenManager tokenManager,
    required final AuthUsers authUsers,
    required final UserProfiles userProfiles,
  }) {
    return EmailPasswordlessIdp(
      this,
      tokenManager: tokenManager,
      authUsers: authUsers,
      userProfiles: userProfiles,
    );
  }
}

/// Creates a new [EmailPasswordlessIdpConfig] instance from keys on the
/// `passwords.yaml` file.
///
/// The pepper is read from the `emailSecretHashPepper` password, the same one
/// that is used by `EmailIdpConfigFromPasswords`.
///
/// This constructor requires that a [Serverpod] instance has already been
/// initialized.
class EmailPasswordlessIdpConfigFromPasswords
    extends EmailPasswordlessIdpConfig {
  /// Creates a new [EmailPasswordlessIdpConfigFromPasswords] instance.
  EmailPasswordlessIdpConfigFromPasswords({
    required super.sendSignUpVerificationCode,
    required super.sendSignInVerificationCode,
    super.fallbackSecretHashPeppers,
    super.secretHashSaltLength,
    super.loginVerificationCodeLifetime,
    super.loginVerificationCodeAllowedAttempts,
    super.loginVerificationCodeGenerator,
    super.failedLoginRateLimit,
    super.loginRequestRateLimit,
    super.resendCooldown,
    super.allowSignUp,
    super.validateEmail,
    super.onBeforeAccountCreated,
    super.onAfterAccountCreated,
    super.onAfterLogin,
  }) : super(
         secretHashPepper: Serverpod.instance.getPasswordOrThrow(
           'emailSecretHashPepper',
         ),
       );
}
