publish_to: none

name: serverpod_cli_e2e_test
version: 1.0.0
description: E2e tests for Serverpod CLI.
repository: https://github.com/serverpod/serverpod

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  async: ^2.11.0
  collection: ^1.17.1
  lints: ^3.0.0
  path: ^1.8.2
  test: ^1.24.2
  uuid: ^3.0.7
  serverpod_cli:
    path: ../.
  serverpod_lints: #1.2.0-rc.1
    path: ../../../packages/serverpod_lints