name: "Serverpod CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  CLAssistant:
    if: github.repository == 'serverpod/serverpod' # skip on forks
    runs-on: ubuntu-latest
    steps:
      - name: "Serverpod CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN : ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          path-to-document: 'https://github.com/serverpod/serverpod/blob/master/CLA.md'
          branch: 'main' # on serverpod/cla_signatures
          remote-organization-name: serverpod
          remote-repository-name:  cla_signatures
